// Zwei Dumme, ein Gedanke – Spicy Intensity 1
// Einfach weitere Texte als neue Zeilen im Array ergänzen.
window.SPICY_LEVEL_1 = [
  'Ein Adjektiv',
  'Ein Albumtitel',
  'Ein alkoholisches Getränk',
  'Ein Berg',
  'Ein Beruf',
  'Ein Brettspiel',
  'Ein Buchstabe',
  'Ein Bundesland',
  'Ein chemisches Element',
  'Ein Dateiformat',
  'Ein Deutschrapper',
  'Ein Disney Charakter',
  'Ein Emoji',
  'Ein Feiertag',
  'Ein Film',
  'Ein Filmcharakter',
  'Ein Filmgenre',
  'Ein Fluss',
  'Ein Frauenname',
  'Ein Fußballer/Fußballerin',
  'Ein Fußballverein',
  'Ein Gegenstand aus Glas',
  'Ein Gegenstand aus Metall',
  'Ein Gegenstand das Licht macht',
  'Ein Gegenstand das warm macht',
  'Ein Gegenstand im Badezimmer',
  'Ein Gegenstand im Büro',
  'Ein Gegenstand, den man im Hotel mitgehen lässt',
  'Ein Gegenstand, den man in der Apotheke kauft',
  'Ein Gemüse',
  'Ein Gerät in der Küche',
  'Ein Gerät zum Putzen',
  'Ein Getränk',
  'Ein Getränk mit Kohlensäure',
  'Ein Handwerksberuf',
  'Ein Haushaltsgerät',
  'Ein Haustier',
  'Ein Influencer/Influencerin',
  'Ein Insekt',
  'Ein Instrument',
  'Ein Jugendwort',
  'Ein Kartenspiel',
  'Ein Kontinent',
  'Ein Körperteil',
  'Ein Kosename',
  'Ein Land',
  'Ein Männername',
  'Ein Märchen',
  'Ein Meerestier',
  'Ein Moderator/Moderatorin',
  'Ein Musikgenre',
  'Ein Nomen',
  'Ein Planet',
  'Ein Pokémon',
  'Ein Politiker/Politikerin',
  'Ein Rapper',
  'Ein Rapper mit einer Zahl im Namen',
  'Ein Raubtier',
  'Ein Sänger/Sängerin',
  'Ein Schauspieler/Schauspielerin',
  'Ein Schimpfwort',
  'Ein Schulfach',
  'Ein Sinnesorgan',
  'Ein Songtitel',
  'Ein Sport',
  'Ein Sportler/Sportlerin',
  'Ein Streamer/Streamerin',
  'Ein Superheld/Superheldin',
  'Ein Supermarkt',
  'Ein Tier auf dem Bauernhof',
  'Ein Tier im Wald',
  'Ein Tier im Wasser',
  'Ein TikToker/TikTokerin',
  'Ein typischer Begriff aus der Geschichte',
  'Ein typischer Begriff aus der Politik',
  'Ein typischer Begriff aus der Wirtschaft',
  'Ein typischer Begriff aus der Wissenschaft',
  'Ein Verb',
  'Ein Videospiel',
  'Ein Wissenschaftler/Wissenschaftlerin',
  'Ein Wort',
  'Ein Wort mit genau 3 Buchstaben',
  'Ein YouTuber/YouTuberin',
  'Eine App',
  'Eine Automarke',
  'Eine Band',
  'Eine Farbe',
  'Eine Fast Food Kette',
  'Eine Schuhgröße',
  'Eine Sehenswürdigkeit',
  'Eine Serie',
  'Eine Sprache',
  'Eine Stadt',
  'Eine Zahl',
];
