// Zwei Dumme, ein Gedanke – Spicy Intensity 2
// Einfach weitere Texte als neue Zeilen im Array ergänzen.
window.SPICY_LEVEL_2 = [
  'Anmachspruch',
'Ausrede für ein abgesagtes Date',
'Bar',
'Beauty-Marke',
'Beziehungsproblem',
'Beziehungsstatus',
'Blume für ein Date',
'Champagnermarke',
'Charaktereigenschaft beim Partner',
'Club',
'Cocktail',
'Cocktailbar',
'Date-Idee',
'Date-No-Go',
'Dating-App',
'Dealbreaker',
'Dessousmarke',
'Emoji zum Flirten',
'Erstes-Date-Ort',
'Fiktiver Crush',
'Fiktives Paar',
'Flirtfehler',
'Flirttechnik',
'Flitterwochenziel',
'Gemeinsames Hobby für Paare',
'Geschenk zum Jahrestag',
'Green Flag',
'Haustiername für den Partner',
'Historisches Liebespaar',
'Hochzeitsbrauch',
'Hochzeitsfarbe',
'Hochzeitslied',
'Hochzeitsort',
'Hotelkette',
'Icebreaker-Frage',
'Kerzenduft',
'Kompliment',
'Körperkontakt',
'Kosename',
'Kosmetikprodukt',
'Kussart',
'Liebesgeste',
'Liebeskomödie',
'Liebeslied',
'Liebessprache',
'Luxushotel',
'Luxusmarke',
'Massageart',
'Massageöl-Duft',
'Modeaccessoire für ein Date',
'Nachricht zum Flirten',
'Nachtleben-Aktivität',
'Ort für einen Heiratsantrag',
'Parfümmarke',
'Pflegeprodukt',
'Picknick-Ort',
'Pornokategorie',
'Promi-Crush',
'Promi-Paar',
'Reality-Datingshow',
'Reality-TV-Paar',
'Red Flag',
'Romantische Aktivität',
'Romantische Serie',
'Romantische Stadt',
'Romantischer Film',
'Romantisches Reiseziel',
'Romantisches Reiseziel in Europa',
'Romantisches Restaurant',
'Schlafbekleidungsstück',
'Schmuckmarke',
'Schokoladenmarke',
'Schuhart fürs Ausgehen',
'Sektmarke',
'Sexstellung',
'Smalltalk-Thema beim Date',
'Social-Media-Plattform zum Kennenlernen',
'Sonnenuntergangs-Spot',
'Spitzname',
'Sternzeichen beim Dating',
'Streitgrund in Beziehungen',
'Traumpartner-Eigenschaft',
'Turn-off',
'Turn-on',
'Überraschung für den Partner',
'Unterwäscheart',
'Urlaub für Paare',
'Valentinstagsgeschenk',
'Verhütungsmethode',
'Verlobungsring-Stil',
'Versöhnungsgeste',
'Weinsorte',
'Wellnessanwendung',
];
