// Zwei Dumme, ein Gedanke – Spicy Intensity 3
// Einfach weitere Texte als neue Zeilen im Array ergänzen.
window.SPICY_LEVEL_3 = [
  {text:"Ein Fetisch.", werWuerdeEher: false},
{text:"Ein Gegenstand für Frauen zum masturbieren.", werWuerdeEher: false},
{text:"Ein Gegenstand für Männer zum masturbieren.", werWuerdeEher: false},
{text:"Ein Gegenstand, den man sich in eine Körperöffnung steckt.", werWuerdeEher: false},
{text:"Ein Ort für einen Quickie.", werWuerdeEher: false},
{text:"Etwas, das man beim Konsum von Pilzen sieht.", werWuerdeEher: false},
{text:"Etwas, das man in einem Sexshop kauft.", werWuerdeEher: false},
{text:"Wer von euch würde der größte Pornostar werden?", werWuerdeEher: true},
{text:"Wer von euch würde eher 1 Flasche Wodka exen?", werWuerdeEher: true},
{text:"Wer von euch würde eher 1 Gramm Koks an einem Abend alleine ziehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher 1 Jahr lang nur in Latex-Klamotten leben?", werWuerdeEher: true},
{text:"Wer von euch würde eher 1 Jahr lang nur noch Hentai-Pornos schauen?", werWuerdeEher: true},
{text:"Wer von euch würde eher 1 Monat lang jeden Tag betrunken sein?", werWuerdeEher: true},
{text:"Wer von euch würde eher 1 Nacht in U-Haft verbringen, weil man nackt durch die Stadt gerannt ist?", werWuerdeEher: true},
{text:"Wer von euch würde eher 1 Woche lang einen Buttplug tragen der alle 5 Stunden Stromschläge verteilt?", werWuerdeEher: true},
{text:"Wer von euch würde eher 1 Woche lang nicht duschen und trotzdem auf Dates gehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher 1 Woche nicht nüchtern verbringen?", werWuerdeEher: true},
{text:"Wer von euch würde eher 10 Snus auf einmal nehmen?", werWuerdeEher: true},
{text:"Wer von euch würde eher 10.000 € in einer Woche versaufen?", werWuerdeEher: true},
{text:"Wer von euch würde eher 24 Stunden komplett nackt verbringen?", werWuerdeEher: true},
{text:"Wer von euch würde eher absichtlich eine Fake-Religion gründen, um Leute auszunutzen?", werWuerdeEher: true},
{text:"Wer von euch würde eher all das eigene Geld beim Glückspiel verlieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher all das eigene Geld im Casino verzocken?", werWuerdeEher: true},
{text:"Wer von euch würde eher als verdeckter Ermittler seine eigene Familie verkaufen?", werWuerdeEher: true},
{text:"Wer von euch würde eher am Familientisch eine erotische Geschichte erzählen?", werWuerdeEher: true},
{text:"Wer von euch würde eher an einem Abend eine ganze Flasche Jägermeister trinken?", werWuerdeEher: true},
{text:"Wer von euch würde eher an einem FKK-Strand einen Antrag machen?", werWuerdeEher: true},
{text:"Wer von euch würde eher an einem öffentlichen Nacktlauf teilnehmen?", werWuerdeEher: true},
{text:"Wer von euch würde eher an einem professionellen Kampf teilnehmen?", werWuerdeEher: true},
{text:"Wer von euch würde eher an einer fremden Socke riechen?", werWuerdeEher: true},
{text:"Wer von euch würde eher an illegalem Glücksspiel teilnehmen?", werWuerdeEher: true},
{text:"Wer von euch würde eher an Kleber schnüffeln, um high zu werden?", werWuerdeEher: true},
{text:"Wer von euch würde eher Arsch lecken?", werWuerdeEher: true},
{text:"Wer von euch würde eher Arschwasser beim Partner attraktiv finden?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf dem Balkon so laut stöhnen, dass die Nachbarn klatschen?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf dem Bürotisch der Kollegen Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf dem Dach eines Hochhauses Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf dem Parkdeck eines Einkaufszentrums Oralsex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf dem Parkplatz eines Supermarkts im Auto Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf dem Schultisch im leeren Klassenzimmer Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf der Club-Toilette beim Koksen vom Türsteher erwischt werden?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf der Tanzfläche Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf die geleakten Nudes eines Influencers masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf die Instagram-Bilder einer bekannten Person masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf die Vorstellung, bei einem Gangbang mitzumachen, masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf Drogen vor der Polizei wegfliegen wollen?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf Ecstasy fremden Leuten die Füße massieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf ein Date mit einem Dealer gehen, um an kostenlose Drogen zu kommen?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf ein Instagram-Bild einer befreundeten Person masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf eine Kinky-Party gehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf eine Schaufensterscheibe schlagen?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einem Baum Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einem Dixi-Klo Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einem Festival Drogen im eigenen Arsch schmuggeln?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einem Festival nackt tanzen?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einem Festival Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einem fremden Balkon Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einem Friedhof nachts masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einem Friedhof nachts Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einem Golfplatz das 18. Loch fingern?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einem Klavier Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einem öffentlichen Spielplatz nachts Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einem Rave 48 Stunden lang durchtanzen ohne Pause?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einem Skilift beim Oralsex fast herunterfallen?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einem Techno-Rave 3 Tage am Stück wach bleiben?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einem Tretboot mitten auf dem See nackt vögeln?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einem Tretboot mitten auf dem See Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einem Trip nackt über die Autobahn laufen?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einen Sex-Chatbot-Betrug reinfallen?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einen Supersportwagen pinkeln?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einer Achterbahn Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einer Beerdigung an einem Flachmann mit Absinth trinken?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einer Beerdigung ein Selfie vor dem Sarg machen?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einer Beerdigung einen Joint rauchen?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einer Beerdigung hinter dem Grabstein Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einer Beerdigung kiffen?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einer Beerdigung masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einer Beerdigung mit dem Pfarrer flirten?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einer Beerdigung mit dem Witwer oder der Witwe flirten?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einer Beerdigung Oralsex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einer Beerdigung Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einer Beerdigung über einen Fetisch sprechen?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einer Clubtoilette masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einer Clubtoilette masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einer Familienfeier eine Line Koks ziehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einer Firmenfeier auf Substanzen masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einer Flugzeug-Toilette Sex mit einer Sexpuppe haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einer Hausparty das Haus anzünden?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einer Hausparty klauen?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einer Hochzeit die Braut oder den Bräutigam anmachen?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einer Klima-Kleber-Blockade sitzen und heimlich Poppers inhalieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einer Müllhalde Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einer öffentlichen Parkbank Oralsex bekommen?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einer öffentlichen Toilette beim Sex von der Polizei erwischt werden?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einer öffentlichen Toilette Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einer Party Analsex in der Küche haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einer Party fremden Personen seine Geschlechtsteile zeigen?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einer Party komplett blankziehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einer Party zu viel trinken und dann ins Bett des Gastgebers pinkeln?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einer Polizeiwache in der Arrestzelle masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einer Schultoilette als Lehrkraft Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einer Skipiste mitten im Schnee Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einer Studentenparty chemische Drogen an Erstsemester verkaufen?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf einer Swinger-Party mit 5 verschiedenen Leuten ungeschützt Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf Koks eine wüste Schlägerei im Club anfangen?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf LSD in einen Spiegel schauen und eine Panikattacke bekommen?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf Magic Mushrooms komplett nackt durch den Wald rennen?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf MDMA in ein Kuscheltier verlieben?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf Pilzen in den Zoo gehen und mit den Tieren reden?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf Pilzen versuchen, mit Tieren im Wald zu sprechen?", werWuerdeEher: true},
{text:"Wer von euch würde eher auf Vinted getragene und ungewaschene Unterwäsche als \"Neu mit Etikett\" verkaufen?", werWuerdeEher: true},
{text:"Wer von euch würde eher aus Hunger Kleber essen?", werWuerdeEher: true},
{text:"Wer von euch würde eher aus Hunger Toilettenpapier essen?", werWuerdeEher: true},
{text:"Wer von euch würde eher aus Spaß im Flieger \"Bombe\" schreien?", werWuerdeEher: true},
{text:"Wer von euch würde eher aus Versehen einen Joint aufessen?", werWuerdeEher: true},
{text:"Wer von euch würde eher aus Versehen Nacktbilder in den Familienchat schicken?", werWuerdeEher: true},
{text:"Wer von euch würde eher bei BeReal beim Oralsex machen?", werWuerdeEher: true},
{text:"Wer von euch würde eher bei der Arbeit saufen?", werWuerdeEher: true},
{text:"Wer von euch würde eher bei einem Bäcker Brötchen klauen?", werWuerdeEher: true},
{text:"Wer von euch würde eher bei einem Einbruch die Hausbesitzer fesseln und ins Gesicht pupsen?", werWuerdeEher: true},
{text:"Wer von euch würde eher bei einem Einbruch in eine Villa ins Bett der Besitzer kacken?", werWuerdeEher: true},
{text:"Wer von euch würde eher bei einem fahrenden Auto aus dem Fenster pinkeln?", werWuerdeEher: true},
{text:"Wer von euch würde eher bei einem Familienessen auf den Tisch kotzen?", werWuerdeEher: true},
{text:"Wer von euch würde eher bei einem Familienessen plötzlich über eigene Kinks reden?", werWuerdeEher: true},
{text:"Wer von euch würde eher bei einem Familienessen über Pornos diskutieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher bei einem Fetisch-Event die Eltern treffen?", werWuerdeEher: true},
{text:"Wer von euch würde eher bei einem Handstand Kokain ziehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher bei einem illegalen Poker-Turnier teilnehmen?", werWuerdeEher: true},
{text:"Wer von euch würde eher bei einem illegalen Straßenrennen ein Polizeiauto rammen?", werWuerdeEher: true},
{text:"Wer von euch würde eher bei einem illegalen Straßenrennen einen Unfall bauen und abhauen?", werWuerdeEher: true},
{text:"Wer von euch würde eher bei einem Krankenwagen klopfen um herauszufinden was los ist?", werWuerdeEher: true},
{text:"Wer von euch würde eher bei einem Porno-Dreh die eigene Familie im Kamera-Team treffen?", werWuerdeEher: true},
{text:"Wer von euch würde eher bei einem Taylor Swift Konzert auf der Toilette rummachen?", werWuerdeEher: true},
{text:"Wer von euch würde eher bei einem Überfall den Fluchtwagen fahren?", werWuerdeEher: true},
{text:"Wer von euch würde eher bei einer Demonstration Dildos auf die Polizei werfen?", werWuerdeEher: true},
{text:"Wer von euch würde eher bei einer Demonstration ein Auto in Brand stecken?", werWuerdeEher: true},
{text:"Wer von euch würde eher bei einer Demonstration Pflastersteine auf die Polizei werfen?", werWuerdeEher: true},
{text:"Wer von euch würde eher bei einer Demonstration Quietscheenten auf die Polizei werfen?", werWuerdeEher: true},
{text:"Wer von euch würde eher bei einer Entführung den Erpresserbrief mit ChatGPT schreiben?", werWuerdeEher: true},
{text:"Wer von euch würde eher bei einer Hausbesetzung die Polizei mit Kuscheltieren abwerfen?", werWuerdeEher: true},
{text:"Wer von euch würde eher bei einer Hausparty Sex im Bett des Gastgebers haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher bei einer illegalen Graffiti-Aktion auf einen fahrenden Zug klettern?", werWuerdeEher: true},
{text:"Wer von euch würde eher bei einer illegalen Poker-Runde mit Mafiamitgliedern mitmachen?", werWuerdeEher: true},
{text:"Wer von euch würde eher bei einer Mutprobe nackt durch einen Supermarkt laufen?", werWuerdeEher: true},
{text:"Wer von euch würde eher bei einer Präsentation Liebeskugeln im Arsch haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher bei einer Razzia aus dem Fenster im 2. Stock springen?", werWuerdeEher: true},
{text:"Wer von euch würde eher bei einer Razzia über die Dächer flüchten?", werWuerdeEher: true},
{text:"Wer von euch würde eher bei einer Schlägerei anfangen die Gegner anzutwerken?", werWuerdeEher: true},
{text:"Wer von euch würde eher bei einer Schlägerei eine Schwimmnudel benutzen?", werWuerdeEher: true},
{text:"Wer von euch würde eher bei einer Verkehrskontrolle Gas geben und eine Sperre durchbrechen?", werWuerdeEher: true},
{text:"Wer von euch würde eher bei Vollmond Sex haben und heiliges Sperma schlucken?", werWuerdeEher: true},
{text:"Wer von euch würde eher beim Flirten einen Porno-Dreh vorschlagen?", werWuerdeEher: true},
{text:"Wer von euch würde eher beim Grenzübertritt Drogen in der Unterwäsche verstecken?", werWuerdeEher: true},
{text:"Wer von euch würde eher beim Gynäkologen oder Urologen bei der kleinsten Berührung kommen?", werWuerdeEher: true},
{text:"Wer von euch würde eher beim illegalen Straßenrennen den eigenen Wagen komplett zu Schrott fahren?", werWuerdeEher: true},
{text:"Wer von euch würde eher beim Kiffen von der Polizei erwischt werden und den Joint herunterschlucken?", werWuerdeEher: true},
{text:"Wer von euch würde eher beim Masturbieren an den Partner des besten Freundes denken?", werWuerdeEher: true},
{text:"Wer von euch würde eher beim Oralsex dem Partner ins Gesicht furzen?", werWuerdeEher: true},
{text:"Wer von euch würde eher beim Oralsex einschlafen?", werWuerdeEher: true},
{text:"Wer von euch würde eher beim Petting im Kino erwischt werden und vom Personal ermahnt werden?", werWuerdeEher: true},
{text:"Wer von euch würde eher beim Sex absichtlich die Fenster offen lassen, damit andere zusehen können?", werWuerdeEher: true},
{text:"Wer von euch würde eher beim Sex aus Versehen \"Mama\" oder \"Papa\" sagen?", werWuerdeEher: true},
{text:"Wer von euch würde eher beim Sex aus Versehen den Namen eines Familienmitglieds sagen?", werWuerdeEher: true},
{text:"Wer von euch würde eher beim Sex das Handy in der Hand behalten, um Benachrichtigungen zu checken?", werWuerdeEher: true},
{text:"Wer von euch würde eher beim Sex das Loch verwechseln?", werWuerdeEher: true},
{text:"Wer von euch würde eher beim Sex ein Kostüm tragen, das der Partner hasst?", werWuerdeEher: true},
{text:"Wer von euch würde eher beim Sex ein Nadelkissen benutzen?", werWuerdeEher: true},
{text:"Wer von euch würde eher beim Sex ein Tier nachspielen?", werWuerdeEher: true},
{text:"Wer von euch würde eher beim Sex eine Handpuppe benutzen und ihr eine Stimme geben?", werWuerdeEher: true},
{text:"Wer von euch würde eher beim Sex eine Tiermaske aus Latex tragen?", werWuerdeEher: true},
{text:"Wer von euch würde eher beim Sex einen Joint rauchen?", werWuerdeEher: true},
{text:"Wer von euch würde eher beim Sex einen Knebel tragen, damit man nicht schreien kann?", werWuerdeEher: true},
{text:"Wer von euch würde eher beim Sex einen Partnertausch mit einem anderen Paar ausprobieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher beim Sex einen Porno anmachen?", werWuerdeEher: true},
{text:"Wer von euch würde eher beim Sex einen Tentakel-Buttplug tragen?", werWuerdeEher: true},
{text:"Wer von euch würde eher beim Sex Elektroschocks genießen?", werWuerdeEher: true},
{text:"Wer von euch würde eher beim Sex heimlich Fotos machen und sie speichern?", werWuerdeEher: true},
{text:"Wer von euch würde eher beim Sex heißes Wachs auf die Genitalien tropfen lassen?", werWuerdeEher: true},
{text:"Wer von euch würde eher beim Sex laut den Namen eines anderen Mitspielers rufen?", werWuerdeEher: true},
{text:"Wer von euch würde eher beim Sex Lebensmittel benutzen?", werWuerdeEher: true},
{text:"Wer von euch würde eher beim Sex mit Eiswürfeln spielen?", werWuerdeEher: true},
{text:"Wer von euch würde eher beim Sex mit heißem Wachs spielen?", werWuerdeEher: true},
{text:"Wer von euch würde eher beim Sex mit Lebensmitteln experimentieren, die danach gemeinsam gegessen werden?", werWuerdeEher: true},
{text:"Wer von euch würde eher beim Sex so heftig kratzen, dass der Partner blutet?", werWuerdeEher: true},
{text:"Wer von euch würde eher beim Strippen auf der Bühne stolpern?", werWuerdeEher: true},
{text:"Wer von euch würde eher beim Zugucken horny werden, wenn der feste Partner geplant mit jemand anderem schläft?", werWuerdeEher: true},
{text:"Wer von euch würde eher beim Zugucken horny werden, wenn der Partner mit einer Person aus dem Freundeskreis schläft?", werWuerdeEher: true},
{text:"Wer von euch würde eher besoffen auf der Arbeit erscheinen?", werWuerdeEher: true},
{text:"Wer von euch würde eher besoffen in eine Polizeikontrolle geraten?", werWuerdeEher: true},
{text:"Wer von euch würde eher besoffen mit einer Kippe im Mund einschlafen?", werWuerdeEher: true},
{text:"Wer von euch würde eher besoffen Ski fahren?", werWuerdeEher: true},
{text:"Wer von euch würde eher besoffen versuchen, einen Dreier zu organisieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher betrunken Auto fahren?", werWuerdeEher: true},
{text:"Wer von euch würde eher betrunken Auto fahren und den Führerschein verlieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher betrunken ein Nude an die komplett falsche Person schicken?", werWuerdeEher: true},
{text:"Wer von euch würde eher betrunken ein Polizeiauto anhalten und nach Ausweis und Fahrzeugpapieren fragen?", werWuerdeEher: true},
{text:"Wer von euch würde eher betrunken einen Autounfall bauen?", werWuerdeEher: true},
{text:"Wer von euch würde eher betrunken Motorrad fahren?", werWuerdeEher: true},
{text:"Wer von euch würde eher betrunken nackt nach Hause laufen?", werWuerdeEher: true},
{text:"Wer von euch würde eher Crack probieren wollen, nur um zu wissen, wie es ist?", werWuerdeEher: true},
{text:"Wer von euch würde eher Crack probieren, wenn absolut niemand davon erfahren würde?", werWuerdeEher: true},
{text:"Wer von euch würde eher das eigene Badewasser verkaufen?", werWuerdeEher: true},
{text:"Wer von euch würde eher das eigene Schlafzimmer in ein Fetisch-Zimmer umwandeln?", werWuerdeEher: true},
{text:"Wer von euch würde eher das ganze Gehalt im Puff ausgeben?", werWuerdeEher: true},
{text:"Wer von euch würde eher das ganze Gehalt im Stripclub ausgeben?", werWuerdeEher: true},
{text:"Wer von euch würde eher das ganze Geld verspielen?", werWuerdeEher: true},
{text:"Wer von euch würde eher das Sexleben der Eltern in einem Podcast besprechen?", werWuerdeEher: true},
{text:"Wer von euch würde eher Dealer werden, wenn die Bezahlung stimmt?", werWuerdeEher: true},
{text:"Wer von euch würde eher Deepfakes von Freunden erstellen?", werWuerdeEher: true},
{text:"Wer von euch würde eher dem Partner ein Selfie von sich und der Scheiße auf der Toilette schicken?", werWuerdeEher: true},
{text:"Wer von euch würde eher den Account eines großen Streamers hacken und rassistische Beleidigungen posten, um ihn zu canceln?", werWuerdeEher: true},
{text:"Wer von euch würde eher den Analplug des Partners ausleihen?", werWuerdeEher: true},
{text:"Wer von euch würde eher den Analplug des Partners ohne dessen Wissen ausleihen?", werWuerdeEher: true},
{text:"Wer von euch würde eher den besten Freund oder die beste Freundin erpressen, um Sex zu bekommen?", werWuerdeEher: true},
{text:"Wer von euch würde eher den Drogenkurier für ein Kartell spielen?", werWuerdeEher: true},
{text:"Wer von euch würde eher den eigenen Ex-Partner im Darknet von Hackern komplett ruinieren lassen?", werWuerdeEher: true},
{text:"Wer von euch würde eher den eigenen Führerschein wegen Trunkenheit am Steuer verlieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher den eigenen Partner beim Sex heimlich filmen und das Video verstecken?", werWuerdeEher: true},
{text:"Wer von euch würde eher den Eltern verschweigen, dass man schon mal harte Drogen probiert hat?", werWuerdeEher: true},
{text:"Wer von euch würde eher den Ex-Partner den Nacktbildern erpressen?", werWuerdeEher: true},
{text:"Wer von euch würde eher den Freunden ohne Grund Arschlochbilder zusenden?", werWuerdeEher: true},
{text:"Wer von euch würde eher den Freunden ohne Grund Fotos des Stuhlgangs zusenden?", werWuerdeEher: true},
{text:"Wer von euch würde eher den Freunden ohne Grund Genitalbilder zusenden?", werWuerdeEher: true},
{text:"Wer von euch würde eher den Führerschein bei einer Polizeikontrolle verlieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher den Fußschweiß von jemand anderem ablecken?", werWuerdeEher: true},
{text:"Wer von euch würde eher den Partner beim Sex verletzen?", werWuerdeEher: true},
{text:"Wer von euch würde eher der Mafia beitreten, wenn sie nett fragen?", werWuerdeEher: true},
{text:"Wer von euch würde eher die eigene Cousine küssen?", werWuerdeEher: true},
{text:"Wer von euch würde eher die eigene Hochzeit auf einem FKK-Strand planen?", werWuerdeEher: true},
{text:"Wer von euch würde eher die eigene Jungfräulichkeit im Internet an den Höchstbietenden versteigern?", werWuerdeEher: true},
{text:"Wer von euch würde eher die eigene Pornosammlung an die Kinder vererben?", werWuerdeEher: true},
{text:"Wer von euch würde eher die eigene Urinprobe manipulieren, um einen Drogentest zu bestehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher die eigenen Fürze verkaufen?", werWuerdeEher: true},
{text:"Wer von euch würde eher die eigenen Nacktbilder als NFTs verkaufen?", werWuerdeEher: true},
{text:"Wer von euch würde eher die Eltern beim Sex erwischen und heimlich weiter zuschauen?", werWuerdeEher: true},
{text:"Wer von euch würde eher die Eltern beim Sex filmen und es für 100 Paletten RedBull verkaufen?", werWuerdeEher: true},
{text:"Wer von euch würde eher die krassesten Sexfantasien ausleben?", werWuerdeEher: true},
{text:"Wer von euch würde eher die Kreditkarte der Eltern klauen, um ein OnlyFans-Imperium zu finanzieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher die meisten Drogen austesten?", werWuerdeEher: true},
{text:"Wer von euch würde eher die Mutter des Partners nackt sehen und es peinlich kommentieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher die Polizei beleidigen?", werWuerdeEher: true},
{text:"Wer von euch würde eher die Popel eines Obdachlosen essen?", werWuerdeEher: true},
{text:"Wer von euch würde eher Dildos in fremden Koffern verstecken?", werWuerdeEher: true},
{text:"Wer von euch würde eher Drogen im Darknet im Wert von über 5.000 Euro bestellen?", werWuerdeEher: true},
{text:"Wer von euch würde eher Drogen im großen Stil über die Grenze schmuggeln?", werWuerdeEher: true},
{text:"Wer von euch würde eher Ecstasy nehmen?", werWuerdeEher: true},
{text:"Wer von euch würde eher Ecstasy nehmen und mit Kuscheltieren eine Orgie starten?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein Alpaka aus dem Zoo klauen, um es an Händler zu verkaufen?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein Anal-Training mit immer größeren Gegenständen machen?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein Auto kurzschließen und damit eine Spritztour machen?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein Bestechungsgeld von 50.000 € an einen Richter zahlen?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein Bewerbungsvideo an eine kriminellen Motorrad-Gang schicken?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein Bordell besuchen?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein Casino in Las Vegas um 1 Million Dollar betrügen?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein Dixi-Klo mit Personen darin umschmeißen?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein Doppelleben mit 2 Familien führen?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein Drogenlabor im eigenen Badezimmer aufbauen?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein Einbrecher Rollenspiel haben und dabei die Tür kaputt machen?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein Escort-Profil mit Bildern der besten Freundin erstellen?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein Fake-Gewinnspiel auf Instagram starten, um an die Bankdaten von Teenagern zu kommen?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein Fake-Profil auf Elite Partner erstellen, um die Treue der eigenen Eltern zu testen?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein ferngesteuertes Sextoy auf der Arbeit tragen und den Chef die App bedienen lassen?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein Foto der eigenen Kackwurst verschicken?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein fremdes Auto auf dem Supermarkt-Parkplatz knacken, nur um darin Sex zu haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein fremdes Haus anzünden, um Versicherungsbetrug zu begehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein fremdes Haustier kidnappen und es selbst behalten, weil es so süß ist?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein gefälschtes Testament einreichen, um ein Erbe zu bekommen?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein geklautes Auto in einem See versenken?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein Gemälde aus einem Museum klauen, es anmalen und wieder zurück bringen?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein gestohlenes Fahrrad auf dem Flohmarkt verkaufen?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein Glory Hole benutzen?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein Halsband tragen und an der Leine durch die Stadt geführt werden?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein illegales Bordell leiten?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein intimes Piercing stechen lassen, das beim Sex extrem wehtut?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein KI-generiertes Profil auf OnlyFans erstellen und Leute abziehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein Kind zeugen und die Vaterschaft einem anderen anhängen?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein Kondom 2-mal benutzen?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein Lehrer-Schüler-Rollenspiel beim Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein OnlyFans-Abo von einer Person haben, die man persönlich kennt?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein Polizeiauto anzünden?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein Polizeiauto klauen und damit durch den McDrive fahren?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein Rollenspiel machen, bei dem man im Rollstuhl sitzt?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein Schneeballsystem gründen?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein Schneeballsystem gründen, um Leute abzuziehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein Sex-Sklave für 1 ganzen Monat sein?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein Sex-Tape drehen und es verlieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein Sex-Tape mit einer Prostituierten drehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein Sex-Tape versehentlich per AirDrop im Zug verschicken?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein Sex-Video von sich selbst an die eigenen Eltern schicken?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein Sextape an die falsche Person schicken?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein Sextape veröffentlichen?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein Sextoy im Laden kaufen?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein Sextoy in der Öffentlichkeit benutzen?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein Sextoy mit jemand anderem teilen?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein sexuelles Geheimnis von jemand anderem ausplaudern?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein teures Auto klauen, nur um eine Spritztour zu machen?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein Video von sich selber beim Masturbieren an den Partner verschicken?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein Video von sich selber beim Masturbieren auf Reddit hochladen?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein Video von sich selber beim Masturbieren veröffentlichen?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein Video von sich selber beim Masturbieren verschicken?", werWuerdeEher: true},
{text:"Wer von euch würde eher ein VR-Sexspiel spielen?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Affäre in der eigenen Wohnung verstecken?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Affäre mit dem Bewährungshelfer anfangen?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Affäre mit dem eigenen Stiefsohn oder der Stieftochter anfangen?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Affäre mit dem Polizisten haben, der einen gerade verhaftet?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Affäre mit dem Therapeuten anfangen?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Affäre mit einem imanigären Freund aufbauen wollen?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Affäre mit einer verheirateten Person anfangen?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Alkoholvergiftung haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Anleitung zum Bombenbau aus dem Internet herunterladen?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Anziehung für alte, faltige Menschen haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Bank ausrauben und unentdeckt bleiben?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Bank überfallen, wenn man wüsste, man kommt damit durch?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Bar im Suff komplett zerstören?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Cannabis-Plantage im Kleiderschrank betreiben?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Droge nehmen, die in Deutschland noch gar nicht bekannt ist?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Ecstasy-Pille vor dem Besuch bei den Großeltern nehmen?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine einstweilige Verfügung bekommen?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Entführung vortäuschen, um Lösegeld von den Eltern zu kassieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Escort-Dame buchen, damit sie beim Umzug nackt mithilft?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Fahndung behindern, indem man Sex mit der gesuchten Person hat?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Fake-Krankheit vortäuschen, um Spenden zu kassieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Fake-Spendenaktion für sich selbst ins Leben rufen und das Geld behalten?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Fetischparty moderieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine fremde Person bitten, einen zu schlagen?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine fremde Pille vom Club-Boden aufheben und schlucken?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine ganze Flasche Wodka auf Ex trinken?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Gaysauna besuchen?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine gefälschte Identität annehmen und jahrelang undercover leben?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine geheime Affäre mit dem eigenen Therapeuten beginnen?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine geheime Affäre starten?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine heimliche Affäre mit einem Promi haben und diese an die Presse verkaufen?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Identität fälschen und 100.000 € Kredit aufnehmen?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Identität fälschen und ein neues Leben unter dem Namen \"Benjamin Blümchen\" beginnen?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine illegale Cannabis-Plantage im Keller der Großeltern betreiben?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine illegale Pokerrunde mit extrem hohen Einsätzen veranstalten?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Kneipenschlägerei anfangen?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine kriminelle Laufbahn einschlagen?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Kunstfälscher-Mafia leiten?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Line Koks vom Hintern eines Elefanten ziehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Line Koks vom Toilettenrand der Club-Toilette lecken?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Line Koks von einer Bibel ziehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Operation ohne Betäubung durchstehen, nur um „hart“ zu wirken?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Person bei OnlyFans für Geld abonnieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Person zur Spielsucht verleiten?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Ping-Pong-Show in Thailand anschauen?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Polygamie-Beziehung eingehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Porno-Karriere haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Porno-Produktion starten und selbst Regie führen?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Pornosammlung an Freunde verschenken?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Prostituierte auf den Mund küssen?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Prostituierte bezahlen, um den eigenen Partner zu verführen?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Prostituierte daten wollen mit dem Gedanken, sie steht auf einen?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Prostituierte für einen Dreier bezahlen und den Partner überzeugen mitzumachen?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Sammlung von Nudes auf dem Handy haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Schlägerei gewinnen?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Schlägerei provozieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Schusswaffe auf dem Schwarzmarkt kaufen und sie als Dildo benutzen?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Schusswaffe illegal zu Hause aufbewahren?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Sex-Party veranstalten?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Sex-Show live auf einer Bühne aufführen, wenn man nicht erkannt wird?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Sexfreundschaft mit dem Ex-Partner eines Freundes haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Sexpuppe für 5.000 € kaufen und sie wie einen echten Partner behandeln?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Sexschaukel ausprobieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Sexsucht entwickeln?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Sucht für Fentanyl entwickeln?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Sucht für illegale Drogen aufbauen?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Sucht für Kokain aufbauen?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Swinger-Party im Elternhaus veranstalten?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Überdosis vortäuschen, um Aufmerksamkeit zu bekommen?", werWuerdeEher: true},
{text:"Wer von euch würde eher eine Vorliebe für Arschwasser entwickeln?", werWuerdeEher: true},
{text:"Wer von euch würde eher einem Fremden Sex in einer dunklen Gasse anbieten?", werWuerdeEher: true},
{text:"Wer von euch würde eher einem illegalen Fight-Club im Keller beitreten?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen alten Schildkrötenpanzer als Aschenbecher benutzen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Analplug bei der Arbeit tragen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Analplug beim Sport tragen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Analplug für 1 Woche am Stück tragen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Analplug für 24 Stunden am Stück tragen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Analplug im Schwimmbad tragen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Analplug tragen, während man bei den Schwiegereltern am Esstisch sitzt?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Ausbruch aus dem Gefängnis planen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Ausweis oder Führerschein fälschen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Banküberfall begehen, nur für den Adrenalinkick?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Banküberfall in einem aufblasbaren T-Rex-Kostüm begehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Banküberfall machen und während der Flucht Stress-Masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Banküberfall mit einer Spielzeugpistole durchführen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Banküberfall mit einer Spielzeugpistole planen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Betrug im Internet ahnungslose Leute abziehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Buttplug bei einem Vorstellungsgespräch tragen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Buttplug benutzen der Stromschläge verteilt?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Buttplug im Fitnessstudio tragen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Cannabiswald im Garten haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Celebrity stalken, bis es eine einstweilige Verfügung gibt?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Dealer ausrauben?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Dealer heiraten, um an kostenlosen Stoff zu kommen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Deepfake-Porno schauen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Diamanten schlucken, um ihn über die Grenze zu schmuggeln?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Dreier haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Dreier mit 2 Escorts haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Dreier mit 2 fremden Leuten haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Dreier mit 2 Geschwistern haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Dreier mit dem Chef oder der Chefin und dessen Ehepartner haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Dreier mit dem Fahrlehrer und dem Prüfer haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Dreier mit den Eltern des besten Freundes haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Dreier mit Zwillingen haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Drogentest mit fremdem Urin fälschen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Drogentrip live auf Social Media streamen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen eigene Scam-Cryptowährung erstellen und sie auf Reddit stellen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Escort-Service für den eigenen Junggesellenabschied buchen und die Firmenkreditkarte nutzen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Escort-Service gründen und der eigene Kunde sein?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Familienurlaub am FKK-Strand machen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Fetisch ausprobieren, der einen selbst überrascht?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Fetisch für Blut haben und sich in einen Vampieren verlieben?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Fetisch für Füße entwickeln?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Feuerlöscher aus einem Fenster werfen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Fremden auf der Straße grundlos anpupsen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Fremden auf der Straße grundlos anrülpsen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Fuchsschwanz beim Sex im Arsch tragen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Gangbang als Junggesellenabschied haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Gangbang mit 5 Fremden haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Gangbang veranstalten?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen gefälschten Ausweis benutzen, um einen hohen Kredit aufzunehmen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen gefälschten Doktortitel kaufen und als Arzt arbeiten?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Geldautomaten mit einem gestohlenen Bagger aus der Wand reißen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Geldtransporter überfallen und das Geld anzünden?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Hacker beauftragen, um die Abschlussnoten zu ändern?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Hacker bezahlen, um das Konto des Chefs leerzuräumen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Hacker im Darknet bezahlen, um das Bankkonto des Ex-Partners zu leeren?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Hackerangriff auf die eigene Firma starten, um das Gehalt zu erhöhen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen illegalen Fight-Club im Keller gründen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen illegalen Rave in einem verlassenen U-Bahn-Schacht organisieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen illegalen Tierhandel mit exotischen Fröschen betreiben?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen illegalen Tierhandel mit exotischen Spinnen betreiben?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen illegalen Waffenhandel im Darknet planen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Joint im Wartezimmer beim Arzt rauchen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Joint rauchen, während man ein Auto fährt?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Kink für Schmerzen haben und sich absichtlich schneiden lassen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Koffer am Flughafen klauen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Koffer mit illegalem Inhalt über die Grenze schmuggeln?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Koffer voller Drogen finden und ihn behalten?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen komplett verbotenen oder unangebrachten Crush haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Mafiaboss als Blödman beleidigen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Mafiaboss bestehlen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen One-Night-Stand im Bett der Eltern haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen One-Night-Stand mit einem Obdachlosen für Geld haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen One-Night-Stand mit jemandem haben, der HIV-positiv ist?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Polizisten mit einem Blowjob bestechen, um einer Strafe zu entgehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Porno auf dem Familienfernseher schauen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Porno auf einer Familienfeier zeigen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Porno in der Bibliothek schauen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Porno in der Öffentlichkeit angucken?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Porno in einem Saal schauen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Porno mit einem der Mitspieler drehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Porno mit einem Elternteil zusammen schauen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Porno nachstellen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Promi stalken und versuchen, ihn persönlich zu treffen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Regenwurm essen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Sex-Livestream starten?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Sex-Roboter ausprobieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Sex-Sklaven oder eine Sex-Sklavin für Geld mieten?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Strap-On ausprobieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Strap-On bei sich selber benutzen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Striptease auf einer Beerdigung hinlegen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Striptease für Fremde aufführen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Swingerclub aufmachen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Tresor mit Dynamit sprengen und dabei den Inhalt kaputt machen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Tunnel graben, um eine Bank auszurauben?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Undercover-Cop enttarnen und erpressen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Unverpacktladen ausrauben und 50kg Kartoffeln klauen, nur für den Adrenalinkick?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Vaterschaftstest fälschen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Versicherungsbetrug in Höhe von 100.000 € durchziehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Vorrat an Drogen im Wert von über 1000 Euro bunkern?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen VR-Porno anschauen?", werWuerdeEher: true},
{text:"Wer von euch würde eher einen Zeugen bedrohen, damit er nicht aussagt?", werWuerdeEher: true},
{text:"Wer von euch würde eher einer alten Oma einen Gehfehler geben?", werWuerdeEher: true},
{text:"Wer von euch würde eher einer Sekte beitreten?", werWuerdeEher: true},
{text:"Wer von euch würde eher einer Sekte beitreten und zum Anfüherer werden?", werWuerdeEher: true},
{text:"Wer von euch würde eher einfach so ein Kind schubsen?", werWuerdeEher: true},
{text:"Wer von euch würde eher es geil finden, wenn der Partner mit dem besten Freund oder der besten Freundin schläft?", werWuerdeEher: true},
{text:"Wer von euch würde eher etwas zu tief in den Arsch schieben und es alleine nicht mehr herausbekommen?", werWuerdeEher: true},
{text:"Wer von euch würde eher Fahrerflucht begehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher Fahrerflucht begehen, nachdem man ein parkendes Auto gerammt hat?", werWuerdeEher: true},
{text:"Wer von euch würde eher fremde Nacktbilder im Internet teilen?", werWuerdeEher: true},
{text:"Wer von euch würde eher fremdgehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher für 1 Gramm Gras sexuelle Handlungen anbieten?", werWuerdeEher: true},
{text:"Wer von euch würde eher für 10.000 € einen Obdachlosen oral befriedigen?", werWuerdeEher: true},
{text:"Wer von euch würde eher für den Playboy posieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher für Drogen das eigene Auto verkaufen?", werWuerdeEher: true},
{text:"Wer von euch würde eher für eine bessere Note Sex mit einer Lehrperson haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher für einen Dreier Geld bezahlen?", werWuerdeEher: true},
{text:"Wer von euch würde eher für einen Filmabend einen Porno vorschlagen?", werWuerdeEher: true},
{text:"Wer von euch würde eher für Geld einen Lapdance geben?", werWuerdeEher: true},
{text:"Wer von euch würde eher für lebenslang gratis Benzin in einem gleichgeschlechtlichen Porno mitspielen?", werWuerdeEher: true},
{text:"Wer von euch würde eher für lebenslang gratis Bier in einem Porno mitspielen?", werWuerdeEher: true},
{text:"Wer von euch würde eher für lebenslang gratis Gras in einem Porno mitspielen?", werWuerdeEher: true},
{text:"Wer von euch würde eher für Pornos bezahlen?", werWuerdeEher: true},
{text:"Wer von euch würde eher für Sex Geld ausgeben?", werWuerdeEher: true},
{text:"Wer von euch würde eher getragene Socken kaufen?", werWuerdeEher: true},
{text:"Wer von euch würde eher getragene Socken verkaufen?", werWuerdeEher: true},
{text:"Wer von euch würde eher getragene Unterwäsche kaufen?", werWuerdeEher: true},
{text:"Wer von euch würde eher getragene Unterwäsche verkaufen?", werWuerdeEher: true},
{text:"Wer von euch würde eher getragene Unterwäsche von Fremden Männern kaufen?", werWuerdeEher: true},
{text:"Wer von euch würde eher Gras mit den Eltern rauchen?", werWuerdeEher: true},
{text:"Wer von euch würde eher grundlos eine Barschlägerei anfangen?", werWuerdeEher: true},
{text:"Wer von euch würde eher grundlos eine Schlägerei im Club anfangen?", werWuerdeEher: true},
{text:"Wer von euch würde eher halbnackt und nur in Unterwäsche in einer Vorlesung sitzen?", werWuerdeEher: true},
{text:"Wer von euch würde eher harte Drogen nehmen?", werWuerdeEher: true},
{text:"Wer von euch würde eher heimlich beim Online-Casino all das eigene Geld verzocken?", werWuerdeEher: true},
{text:"Wer von euch würde eher heimlich die Schuhe von Arbeitskollegen beschnuppern?", werWuerdeEher: true},
{text:"Wer von euch würde eher heimlich die Zahnbürste vom Crush benutzen?", werWuerdeEher: true},
{text:"Wer von euch würde eher heimlich fremde Sextoys benutzen?", werWuerdeEher: true},
{text:"Wer von euch würde eher heimlich Screenshots von Nudes machen?", werWuerdeEher: true},
{text:"Wer von euch würde eher Hentai-Pornos schauen?", werWuerdeEher: true},
{text:"Wer von euch würde eher horny werden, wenn der Partner mit einem Kollegen oder einer Kollegin schläft?", werWuerdeEher: true},
{text:"Wer von euch würde eher illegale Pyrotechnik im Fußballstadion zünden?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Auto Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Badezimmer eines Freundes Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Beichtstuhl der Kirche Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Beichtstuhl masturbieren und anfangen laut zu stöhnen?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Bett neben jemand anderem masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Bordell einen kompletten Monatslohn an einem Abend ausgeben?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Büro Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Casino das meiste Geld verlieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Casino Drogen nehmen, um konzentrierter zu sein?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Chefsessel im Büro Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Club jemanden abschleppen und später feststellen, dass es ein Verwandter ist?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Darknet illegale Sachen bestellen?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Disneyland Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Drogenrausch das eigene Auto verschenken?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Drogenrausch eine Bank überfallen wollen?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Fahrstuhl Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Flughafen wegen Terrorverdacht kontrolliert werden?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Flugzeug auf der Toilette Koks ziehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Gefängnis landen?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Gefängnis landen und dort eine Bande gründen?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Gym eine Hartalkohol mische trinken?", werWuerdeEher: true},
{text:"Wer von euch würde eher im ICE auf der Toilette Kokain ziehen und erwischt werden?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Keller der Nachbarn Sex haben, während diese oben fernsehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Kino während eines Horrorfilms masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Krankenhaus auf der Intensivstation Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Lotto gewinnen und alles versaufen?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Meer beim Sex von einer Qualle gestochen werden?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Meer masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Museum masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Museum Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Schlaf wegen zu viel Alkohol kotzen?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Schwimmbad auf dem Sprungturm nachts Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Stadion einen Flitzer machen?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Stadion nackt einen Flitzer machen?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Suff harte Drogen für 1.000 € kaufen?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Suff harte Drogen probieren, die man eigentlich ablehnt?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Taxi heftig rummachen, während der Fahrer alles sieht?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Treppenhaus der eigenen Wohnung Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Wald beim Sex von Pilzsammlern erwischt werden?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Zimmer der Eltern Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Zoo vor dem Affengehege Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher im Zug Pornos schauen?", werWuerdeEher: true},
{text:"Wer von euch würde eher in das Haus des Ex-Partners einbrechen, um Sachen zu zerstören?", werWuerdeEher: true},
{text:"Wer von euch würde eher in den Pool kacken?", werWuerdeEher: true},
{text:"Wer von euch würde eher in der Bibliothek zwischen den Regalen masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher in der Dusche des Fitnessstudios mit einem der Mitspieler Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher in der Kirche masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher in der Öffentlichkeit laut über Fetische diskutieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher in der Öffentlichkeit masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher in der Umkleidekabine eines Schwimmbads Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher in der Wildnis masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher in die Dusche kacken?", werWuerdeEher: true},
{text:"Wer von euch würde eher in ein Gebäude einbrechen?", werWuerdeEher: true},
{text:"Wer von euch würde eher in ein Gebäude einbrechen, um dort zu masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher in ein Hotelzimmer einbrechen?", werWuerdeEher: true},
{text:"Wer von euch würde eher in ein Museum einbrechen?", werWuerdeEher: true},
{text:"Wer von euch würde eher in ein Museum einbrechen und dort masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher in ein Schwimmbad einbrechen und dort Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher in ein Schwimmbad einbrechen, um dort zu masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher in eine Gaysauna gehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher in eine Schlägerei geraten?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einem Club Bong rauchen?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einem Darkroom auf einer Fetisch-Party mit 3 Fremden rummachen?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einem Darkroom mit jemand Fremdem Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einem Dixi-Klo auf einem Festival Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einem fahrenden Zug Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einem Familienurlaub LSD nehmen?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einem Fetisch-Forum Mitglied sein?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einem Freibad auf der Wiese masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einem Freibad auf der Wiese Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einem fremden Bett Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einem fremden Hotelzimmer Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einem fremden Land festgenommen werden?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einem Geschäft Klamotten klauen?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einem Kornfeld beim Sex einen Maiskomel in den Arsch schieben?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einem Laden etwas kaputt machen und nicht bezahlen?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einem Maislabyrinth Oralsex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einem Museum ein Gemälde anmastubieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einem Museum hinter einer Statue masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einem öffentlichen Verkehrsmittel Sex haben, ohne erwischt zu werden?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einem Porno mitspielen, nur um berühmt zu werden?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einem Porno-Casting landen, ohne es zu merken?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einem Riesenrad auf dem Jahrmarkt Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einem Schwimmbad masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einem Sex-Club feiern?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einem Sexshop einen Minijob haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einem Sexshop nach Rabatt fragen?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einem stillstehenden Zug masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einem stillstehenden Zug Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einem Stripclub arbeiten?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einem Supermarkt auf den Boden pissen?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einem Traum Sex mit einem Familienmitglied haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einem vollen Bus masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einen Hoteltresor kacken?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einen stillstehenden Zug einbrechen?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einen Stripclub gehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einen Swingerclub gehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einer Arztpraxis masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einer Arztpraxis Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einer Autowaschanlage im Auto Oralsex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einer Beziehung heimlich eine Affäre mit jemandem aus dem Bekanntenkreis haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einer Beziehung Nacktbilder an andere verschicken?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einer Burgruine Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einer Fabrik masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einer Fotokabine Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einer Karaoke-Bar einen Song singen, der alle verstört?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einer Kirche Pornos drehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einer leeren Kirche auf dem Altar Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einer öffentlichen Toilette masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einer raucherfreien Zone Gras rauchen?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einer Sauna masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einer Sauna Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einer Schwimmbadkabine masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einer Schwimmbadkabine Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einer Seilbahn-Gondel Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einer Telefonzelle Oralsex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einer Therme masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einer Tropfsteinhöhle Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einer Umkleidekabine beim Sex vom Personal erwischt werden?", werWuerdeEher: true},
{text:"Wer von euch würde eher in einer Zugtoilette masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher in Tigergehege einbrechen um ihn zu streicheln?", werWuerdeEher: true},
{text:"Wer von euch würde eher in Unterwäsche Schlitten fahren?", werWuerdeEher: true},
{text:"Wer von euch würde eher in Unterwäsche Schlittschuh fahren?", werWuerdeEher: true},
{text:"Wer von euch würde eher in Unterwäsche Ski fahren gehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher innerhalb von 24 Stunden, mit 2 verschiedenen Menschen Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher jemandem beim Sex ins Gesicht spucken?", werWuerdeEher: true},
{text:"Wer von euch würde eher jemanden anbaggern, der schon vergeben ist?", werWuerdeEher: true},
{text:"Wer von euch würde eher jemanden auf einem Riesenrad Oralsex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher jemanden auf einer Beerdigung anflirten?", werWuerdeEher: true},
{text:"Wer von euch würde eher jemanden beim Sex beobachten und dabei masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher jemanden beim Sex würgen und dabei geil werden?", werWuerdeEher: true},
{text:"Wer von euch würde eher jemanden bestechen, um den eigenen Willen zu bekommen?", werWuerdeEher: true},
{text:"Wer von euch würde eher jemanden daten, der vergeben ist?", werWuerdeEher: true},
{text:"Wer von euch würde eher jemanden fisten?", werWuerdeEher: true},
{text:"Wer von euch würde eher jemanden heimlich beim Masturbieren beobachten?", werWuerdeEher: true},
{text:"Wer von euch würde eher jemanden im Club küssen, obwohl man in einer Beziehung ist?", werWuerdeEher: true},
{text:"Wer von euch würde eher jemanden im Darknet verarschen und Geld abziehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher jemanden im Schlaf küssen?", werWuerdeEher: true},
{text:"Wer von euch würde eher jemanden mit Sperma im Gesicht wecken oder geweckt werden?", werWuerdeEher: true},
{text:"Wer von euch würde eher jemanden während des Sex fesseln?", werWuerdeEher: true},
{text:"Wer von euch würde eher Ketamin auf einer Hausparty verteilen?", werWuerdeEher: true},
{text:"Wer von euch würde eher Kokain in der Kirche ziehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher Kokain von den Brüsten einer Prostituierten ziehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher Koks ziehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher Kunstwerke aus einer Galerie vollkritzeln?", werWuerdeEher: true},
{text:"Wer von euch würde eher Kupferkabel von Bahngleisen stehlen und es verkaufen?", werWuerdeEher: true},
{text:"Wer von euch würde eher lieber Urin als Fleisch zu sich nehmen?", werWuerdeEher: true},
{text:"Wer von euch würde eher Liebeskugeln bei der Arbeit tragen?", werWuerdeEher: true},
{text:"Wer von euch würde eher Liebeskugeln benutzen?", werWuerdeEher: true},
{text:"Wer von euch würde eher Liebeskugeln für sich selbst nutzen?", werWuerdeEher: true},
{text:"Wer von euch würde eher LSD auf einer Beerdigung nehmen?", werWuerdeEher: true},
{text:"Wer von euch würde eher LSD in den morgendlichen Kaffee mischen?", werWuerdeEher: true},
{text:"Wer von euch würde eher Medikamente fälschen und verkaufen?", werWuerdeEher: true},
{text:"Wer von euch würde eher mehrere Leute gleichzeitig befriedigen?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit 2 Geschwistern gleichzeitig eine Affäre führen?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit 2 Geschwistern schlafen, ohne dass sie es wissen?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit 2 verschiedenen Personen Sex haben, ohne zu duschen?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit 5 verschiedenen Menschen innerhalb von 24 Stunden Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit Autopilot bei 230 km/h auf der Autobahn Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit dem Anwalt des Partners schlafen, um Vorteile bei der Scheidung zu kriegen?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit dem Chef oder der Chefin der Konkurrenzfirma schlafen, um Firmengeheimnisse zu klauen?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit dem Chef oder der Chefin Sex haben, um eine Gehaltserhöhung zu bekommen?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit dem eigenen Anwalt Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit dem eigenen Chef oder der Chefin auf der Firmen-Weihnachtsfeier rummachen?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit dem eigenen Klon Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit dem Ex-Partner der Mutter oder dem Vater Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit dem Ex-Partner des eigenen Bruders oder der Schwester schlafen?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit dem Fahrlehrer Sex haben, um den Führerschein zu bestehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit dem Geschwisternteil des Partners fremdgehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit dem Gynäkologen während der Sprechstunde Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit dem Hochzeitsfotografen einen Quickie haben, bevor man zum Traualtar schreitet?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit dem Partner auf eine Fetischparty gehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit dem Partner eines Mitspielers flirten?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit dem Partner zusammen an einer Orgie teilnehmen?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit dem Pfarrer der eigenen Gemeinde Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit dem Stiefvater oder der Stiefmutter schlafen?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit den Eltern an einen FKK-Strand gehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit den Eltern der Person links von sich Analsex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit den Eltern der Person links von sich Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit den Eltern der Person rechts von sich eine Sexfreundschaft haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit den Geschwistern der Person links von sich Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit der Cousine oder dem Cousin ersten Grades Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit der Mutter oder dem Vater des besten Freundes schlafen?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit der Person links von sich Analsex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit der Person links von sich einen Dreier haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit der Person rechts von sich auf eine Sexparty gehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit der Person rechts von sich Gruppensex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit der Person rechts von sich in eine Gaysauna gehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit einem 1-zu-1-Klon von sich selber Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit einem Ex-Partner schlafen, während dieser in einer neuen Beziehung ist?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit einem Fremden rummachen?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit einem Gegenstand verheiratet sein?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit einem Obdachlosen für Geld Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit einem Sexpartner ein Konto bei OnlyFans starten?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit einem Verbrecher eine Affäre haben und für Sex ins Gefängnis fahren?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit einem verurteilten Mörder im Gefängnis Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit einer 80-jährigen Person schlafen?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit Falschgeld in einem Club bezahlen?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit jemandem auf der Clubtoilette vögeln, den man gerade erst kennengelernt hat?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit jemandem schlafen, obwohl man weiß, dass die Person in einer Beziehung ist?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit jemandem Sex haben, um sich einen Karrierevorteil zu verschaffen?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit KI Nacktbilder erstellen?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit KI-Pornos Geld verdienen?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit Lebensmitteln beim Oralsex experimentieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit mehreren Leuten gleichzeitig Oralsex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher mit mehreren Personen gleichzeitig rummachen?", werWuerdeEher: true},
{text:"Wer von euch würde eher nach 4 Tagen wach Halluzinationen bekommen und mit Bäumen reden?", werWuerdeEher: true},
{text:"Wer von euch würde eher nach dem Arschlecken Zungenküsse verteilen?", werWuerdeEher: true},
{text:"Wer von euch würde eher nach einem Autounfall Fahrerflucht begehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher nach einem Besuch im Stripclub von der Familie erwischt werden?", werWuerdeEher: true},
{text:"Wer von euch würde eher nach einem One-Night-Stand den Schmuck der Person klauen?", werWuerdeEher: true},
{text:"Wer von euch würde eher nachts in ein Gebäude einbrechen, um dort Sex zu haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher nachts in ein Museum einbrechen, um dort Sex zu haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher nachts in ein Schwimmbad einbrechen?", werWuerdeEher: true},
{text:"Wer von euch würde eher nachts in einen Zoo einbrechen und Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher nackt auf einer Bühne auftreten?", werWuerdeEher: true},
{text:"Wer von euch würde eher nackt durch die Nachbarschaft laufen?", werWuerdeEher: true},
{text:"Wer von euch würde eher nackt durch ein Hotel laufen, weil man den Schlüssel verloren hat?", werWuerdeEher: true},
{text:"Wer von euch würde eher nackt durch einen vollen Zug rennen?", werWuerdeEher: true},
{text:"Wer von euch würde eher nackt eine Bank überfallen?", werWuerdeEher: true},
{text:"Wer von euch würde eher nackt einen Marathon laufen?", werWuerdeEher: true},
{text:"Wer von euch würde eher nackt im Theater auf der Bühne tanzen?", werWuerdeEher: true},
{text:"Wer von euch würde eher nackt in einer Reality-Show mitmachen?", werWuerdeEher: true},
{text:"Wer von euch würde eher Nacktbilder an jemanden schicken, den man erst 1 Tag kennt?", werWuerdeEher: true},
{text:"Wer von euch würde eher Nacktbilder des Ex-Partners veröffentlichen?", werWuerdeEher: true},
{text:"Wer von euch würde eher Nacktbilder in der Story posten?", werWuerdeEher: true},
{text:"Wer von euch würde eher Nippelbilder gegen Bier tauschen?", werWuerdeEher: true},
{text:"Wer von euch würde eher Nippelbilder gegen Gras tauschen?", werWuerdeEher: true},
{text:"Wer von euch würde eher Nudes an eine Autoritätsperson für eine bessere Bewertung schicken?", werWuerdeEher: true},
{text:"Wer von euch würde eher Nudes an einen Arbeitskollegen schicken?", werWuerdeEher: true},
{text:"Wer von euch würde eher Nudes aus Versehen in eine Arbeitsgruppe schicken?", werWuerdeEher: true},
{text:"Wer von euch würde eher Nudes aus Versehen in einen Gruppenchat schicken?", werWuerdeEher: true},
{text:"Wer von euch würde eher nur für Sex in ein anderes Land reisen?", werWuerdeEher: true},
{text:"Wer von euch würde eher nur in Unterwäsche zur Uni oder zur Arbeit gehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher ohne Führerschein ein Auto fahren?", werWuerdeEher: true},
{text:"Wer von euch würde eher Öl ins Meer kippen?", werWuerdeEher: true},
{text:"Wer von euch würde eher OnlyFans machen?", werWuerdeEher: true},
{text:"Wer von euch würde eher Oralsex im Skilift haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher Oralsex im Stadium während eines Spiels haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher Oralsex in einer Gondel haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher Oralsex mit dem Chef oder der Chefin haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher Oralsex mit einer Person haben, die vergeben ist?", werWuerdeEher: true},
{text:"Wer von euch würde eher Pegging ausprobieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher Pilze vor einem wichtigen Bewerbungsgespräch nehmen?", werWuerdeEher: true},
{text:"Wer von euch würde eher Pornos drehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher Pornos mit Freunden zusammen schauen?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex auf einem Boot haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex auf einem Dach haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex auf einem Dixi-Klo haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex auf einem Trampolin ausprobieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex bei einem Feldpicknick haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex im Auto während der Fahrt haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex im Club haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex im Elternbett haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex im Haus eines Mitspielers haben, ohne dass dieser es weiß?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex im Skilift haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex im Umkleideraum haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex im Wald haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex im Zelt auf einem Festival haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex in der Natur haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex in der Öffentlichkeit haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex in einem Beichtstuhl haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex in einem Flugzeug haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex in einem Krankenhausbett haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex in einem Polizeiauto haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex in einem Schwimmbad haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex in einem Taxi haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex in einer Fabrik haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex in einer Gondel haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex in einer Sauna haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex in einer Therme haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex mit dem Crush von einem der Mitspieler haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex mit einem anderen Paar haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex mit einem der Mitspieler haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex mit einem Minion haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex mit einer 18-Jährigen Person haben, wenn man selbst 50 ist?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex mit einer 30 Jahre älteren Person haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex mit einer 80-jährigen Person haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex mit einer alten, faltigen und muffigen Person haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex mit einer Oma oder einem Opa haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex mit einer Prostituierten haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex mit einer Sexpuppe haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex mit jemandem haben, während eine andere Person im selben Raum zuschaut?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex mit Lebensmitteln haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex unter einer Brücke haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex vor einer Webcam für Geld anbieten?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sex vor Überwachungskameras haben, um sich dabei beobachtet zu fühlen?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sextapes mit dem Ex-Partner veröffentlichen?", werWuerdeEher: true},
{text:"Wer von euch würde eher Sextoys mit Freunden teilen?", werWuerdeEher: true},
{text:"Wer von euch würde eher sich und den Partner heimlich beim Sex filmen?", werWuerdeEher: true},
{text:"Wer von euch würde eher so hart saufen und im Krankenhaus landen?", werWuerdeEher: true},
{text:"Wer von euch würde eher so hart saufen, dass man im Krankenhaus mit einer Alkoholvergiftung aufwacht?", werWuerdeEher: true},
{text:"Wer von euch würde eher so richtig berühmt durch Pornos werden?", werWuerdeEher: true},
{text:"Wer von euch würde eher so stark kiffen, dass man den eigenen Namen vergisst?", werWuerdeEher: true},
{text:"Wer von euch würde eher Speed ziehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher Stammkunde im Puff werden?", werWuerdeEher: true},
{text:"Wer von euch würde eher Stammkunde in einem Sexshop werden?", werWuerdeEher: true},
{text:"Wer von euch würde eher Stammkunde in einem Stripclub werden?", werWuerdeEher: true},
{text:"Wer von euch würde eher Steuerhinterziehung begehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher Straßenschilder mitnehmen?", werWuerdeEher: true},
{text:"Wer von euch würde eher Straßenschilder vertauschen und den Straßenverkehr damit gefährden?", werWuerdeEher: true},
{text:"Wer von euch würde eher Strip-Poker spielen?", werWuerdeEher: true},
{text:"Wer von euch würde eher Trainsurfing als Hobby haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher trotz Periode Oralsex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher Verletzungen nach dem Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher versuchen, mit dem Richter während des eigenen Prozesses zu flirten?", werWuerdeEher: true},
{text:"Wer von euch würde eher versuchen, über ein fahrendes Auto zu springen?", werWuerdeEher: true},
{text:"Wer von euch würde eher veruchen einen Geldautomaten mit Feuerwerk zu sprengen?", werWuerdeEher: true},
{text:"Wer von euch würde eher voll auf Drogen Auto fahren?", werWuerdeEher: true},
{text:"Wer von euch würde eher vom Zugucken horny werden, wenn der feste Partner mit dem Ex-Partner schläft?", werWuerdeEher: true},
{text:"Wer von euch würde eher von der Polizei verhaftet werden?", werWuerdeEher: true},
{text:"Wer von euch würde eher von einem Fahrgeschäft auf Menschen spucken?", werWuerdeEher: true},
{text:"Wer von euch würde eher vor dem Sex Viagra nehmen?", werWuerdeEher: true},
{text:"Wer von euch würde eher während der Autofahrt die fahrende Person befriedigen?", werWuerdeEher: true},
{text:"Wer von euch würde eher während des Rollenspiels die Rolle vergessen?", werWuerdeEher: true},
{text:"Wer von euch würde eher während des Sex den Partner beleidigen?", werWuerdeEher: true},
{text:"Wer von euch würde eher während des Sex extreme Schimpfwörter benutzen?", werWuerdeEher: true},
{text:"Wer von euch würde eher während einer Onlinevorlesung komplett nackt und auf Pilzen sein?", werWuerdeEher: true},
{text:"Wer von euch würde eher während einer Untersuchung mit dem ärztlichen Personal flirten?", werWuerdeEher: true},
{text:"Wer von euch würde eher während eines Dreiers einschlafen?", werWuerdeEher: true},
{text:"Wer von euch würde eher während eines Familienessens jemanden unter dem Tisch befriedigen?", werWuerdeEher: true},
{text:"Wer von euch würde eher während eines Fußballspiels im Stadion auf der Toilette Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher während eines Gangbangs den falschen Namen stöhnen?", werWuerdeEher: true},
{text:"Wer von euch würde eher während eines normalen Video-Calls masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher während eines Telefonats mit dem Chef oder der Chefin masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher während eines Telefonats mit dem Chef oder der Chefin Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher während eines Telefonats mit der Familie masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher während eines Telefonats mit der Familie Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde eher warten, bis eine Person schläft, um an dieser zu riechen?", werWuerdeEher: true},
{text:"Wer von euch würde eher wegen einer verlorenen Wette nackt durch die Stadt rennen?", werWuerdeEher: true},
{text:"Wer von euch würde eher wegen eines Sex-Unfalls im Krankenhaus enden?", werWuerdeEher: true},
{text:"Wer von euch würde eher wegen Trunkenheit am Arbeitsplatz gekündigt werden?", werWuerdeEher: true},
{text:"Wer von euch würde eher Wodka durch die Nase ziehen?", werWuerdeEher: true},
{text:"Wer von euch würde eher zu einem Deepfake-Porno masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher zu einem VR-Porno masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde eher zu Hentai-Pornos masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde für das wenigste Geld den eigenen Körper verkaufen?", werWuerdeEher: true},
{text:"Wer von euch würde Sex mit der hässlichsten Person haben?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher absichtlich verprügeln lassen, nur um zu wissen, wie es ist?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher auf der Arbeit masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher auf Drogen mit Kuscheltieren kuscheln?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher auf einem Musikfestival als Sanitäter ausgeben, um an Medikamente zu kommen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher auf einem Riesenrad beim Sex fast aus der Gondel stürzen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher auf einem Taylor Swift Konzert Ecstasy nehmen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher auf einem Trip einbilden, fliegen zu können?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher auf einer Dating-App als das eigene Haustier ausgeben?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher auf einer Hochzeit nackt zeigen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher auf einer Kinky-Party nackt an ein Andreaskreuz fesseln lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher auf einer Party nackt als Tisch benutzen lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher auf einer Rolltreppe im Kaufhaus unter den Rock fassen lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher auf LSD die Haare komplett abrasieren, und die Kopfhaut Pink anmalen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher auf MDMA in einen Baum verlieben?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher bei der Abschlssfeier in einem Latexanzug auftauchen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher bei einem Dreier mehr auf den Partner des eigenen Geschlechts konzentrieren?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher bei einem Dreier nicht vom Sexpartner des eigenen Geschlechts anfassen lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher bei einer Flucht vor der Polizei in die Hose kacken und nackt weiter laufen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher bei einer Schlägerei nackt ausziehen, um den Gegner zu verwirren?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Auto fahren hinter dem Steuer selbst befriedigen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Klippenspringen verletzen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Masturbieren beobachten lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Masturbieren einen Finger in den Arsch stecken?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Masturbieren Eiswürfel in den Arsch schieben?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Masturbieren selber schlagen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Oralsex so fest ohrfeigen lassen, dass die Lippe aufplatzt?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Rollenspiel im Bett als Arzt oder Krankenschwester verkleiden?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Schauen von \"Fifty Shades of Grey\" wie ein BDSM-Profi aufspielen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Sex 1 VR-Brille aufsetzen und mit einem Animecharakter Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Sex absichtlich erwischen lassen, nur für den Kick?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Sex absichtlich Verletzungen zufügen lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Sex anal befriedigen lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Sex auspeitschen lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Sex beleidigen lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Sex beleidigen lassen und es anziehend finden?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Sex beobachten lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Sex bewegungsunfähig fesseln lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Sex büschelweise die Haare ausreißen lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Sex den ganzen Körper mit Frischhaltefolie einwickeln lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Sex die Haare rasieren lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Sex die Nippel anbeißen lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Sex die Nippel mit Klammern abklemmen lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Sex einen Knebel in den Mund stecken lassen, bis man sabbert?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Sex Eiswürfel in den Arsch schieben lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Sex Eiswürfeln einführen lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Sex erniedrigen lassen, um den Partner sexuell zu erregen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Sex filmen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Sex in einen dunklen Raum sperren lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Sex in einen Hundekäfig einsperren lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Sex ins Gesicht spucken lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Sex mit dem Ex-Partner filmen lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Sex mit Lebensmitteln vollschmieren lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Sex selbst tattoowieren?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Sex so verletzen, dass der Krankenwagen gerufen werden muss?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Sex verletzen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Sex von 3 Leuten gleichzeitig anspucken lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Sex von den Nachbarn beobachten lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Sex von einem Hund zuschauen lassen und es geil finden?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Sex würgen lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher beim Sex würgen lassen, bis man fast ohnmächtig wird?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher die Nippel mit Gewichten beschweren lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher ein Intimpiercing stechen lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher ein Tattoo im Intimbereich stechen lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher eine illegale Substanz spritzen lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher eine Massage mit Happy Ending geben lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher eine Zigarette auf dem Arm ausdrücken?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher erregt fühlen, wenn der Partner mit dem Nachbarn oder der Nachbarin schläft?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher fisten lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher für 10.000 € pro Tag jede Woche einmal ins Gesicht kacken lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher für 5.000 € auf einer Webcam-Seite komplett nackt ausziehen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher für den Partner ein Intimpiercing machen lassen, obwohl man es selber nicht mag?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher für Geld auf einer Webcam-Seite masturbieren?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher getragene und ungewaschene Unterwäsche online an Fetischisten verkaufen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher im Bett komplett wie eine Sexpuppe behandeln lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher im Bett wie ein Hund an der Leine führen lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher im Hotel nackt auf dem Buffet-Tisch servieren lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher im IKEA nackt in ein Bett legen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher im Schlafzimmer einen Käfig aufbauen, um darin eingesperrt zu werden?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher im sexuellen Kontext mit Absicht verletzen lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher im Suff ein Intimpiercing stechen lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher im Suff ein teures Luxusauto über Klarna auf Raten kaufen und danach untertauchen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher in einem Fetischclub anmelden?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher in einem Museum vor einer Statue selbst befriedigen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher in einen Pornostar verlieben?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher in einen Verwandten verlieben?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher in einer religiösen Einrichtung entblößen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher mit einem anonymen Fremden in einem Chatroom verabreden?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher mit einem Drogendealer anfreunden?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher mit einem Musikinstrument selbst befriedigen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher mit Lebensmitteln selbst befriedigen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher mithilfe von Zeitreisen in der Vergangenheit mit sich selbst Sex haben?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher nach dem Sex die Augen für 24 Stunden verbinden lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher Nadeln durch die Nippel stechen lassen, um Lust zu empfinden?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher selber auspeitschen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher selbst anal befriedigen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher selbst beim Masturbieren anal befriedigen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher selbst ein Nippelpiercing stechen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher selbst eine Bierflasche am Kopf zerschlagen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher selbst prostituieren, um etwas Geld zum Feiern zu bekommen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher vom eigenen Crush in den Mund spucken lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher vom Partner mit einem Strap-on dominieren lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher von 2 Männern gleichzeitig penetrieren lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher von der Person links von sich anspucken lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher von der Person links von sich oral befriedigen lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher von der Person rechts von sich den Arsch auspeitschen lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher von der Person rechts von sich den Intimbereich rasieren lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher von einem Fremden im Park fesseln lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher von einem Sugar-Daddy den kompletten Lebensunterhalt finanzieren lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher von einem völlig Unbekannten auf der Herrentoilette kitzeln lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher von einer Domina finanziell ausbeuten lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher von festen Schlägen sexuell angezogen fühlen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher von Thanos fisten lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher vor der Webcam ausziehen und das streamen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher während des Sex anspucken lassen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher während des Sex verletzen und trotzdem weitermachen?", werWuerdeEher: true},
{text:"Wer von euch würde sich eher während eines Twitch-Livestreams heimlich unter dem Tisch befriedigen lassen?", werWuerdeEher: true},
{text:"Wer von euch würde während eines Abends im Club mit den meisten rummachen?", werWuerdeEher: true},
{text:"Wo landet das Sperma am liebsten beim Sex.", werWuerdeEher: false}
];
