// Inhalte für Spicy Intensity Level 2.
window.SPICY_LEVEL_2 = [
  'Ein Begriff den man hauptsächlich nur im Schlafzimmer benutzt...',
  'Ein Begriff für jemanden der nur auf das Eine aus ist...',
  'Ein ekliger Fund im Kühlschrank...',
  'Ein ekliger Fund in einer Restaurantküche...',
  'Ein Emoji mit zweideutiger Bedeutung...',
  'Ein Gefühl das man oft betrunken hat...',
  'Ein Gefühl nach zu viel Alkohol...',
  'Ein Gegenstand den man typischerweise beim Sex im Mund haben kann...',
  'Ein Gegenstand, den man für ein Rollenspiel braucht...',
  'Ein Gleitmittel-Ersatz...',
  'Ein Grund für eine Anzeige...',
  'Ein Grund für eine Notlüge beim Partner...',
  'Ein Grund für eine peinliche Erektion...',
  'Ein Grund für eine sofortige Blockierung...',
  'Ein Grund für eine sofortige Scheidung vor dem Altar...',
  'Ein Grund für einen Strafzettel...',
  'Ein Grund fürs nicht kommen können...',
  'Ein Grund fürs Stöhnen...',
  'Ein Grund fürs zu früh kommen...',
  'Ein Grund jemanden eifersüchtig zu machen...',
  'Ein Grund jemanden heiß zu finden...',
  'Ein Grund jemanden nackt sehen zu wollen...',
  'Ein Grund jemanden zu beleidigen...',
  'Ein Grund warum man beim Küssen die Augen weit offen lässt...',
  'Ein Grund warum man beim Sex die Socken anlässt...',
  'Ein Grund warum man beim Sex plötzlich lachen muss...',
  'Ein Grund warum man beim Sexting ein altes Bild schickt...',
  'Ein Grund warum man beim Vorspiel plötzlich aufhören muss...',
  'Ein Grund warum man die Nummer eines Dates sofort blockiert...',
  'Ein Grund warum man ein Aktfoto von sich löscht...',
  'Ein Grund warum man eine Dating-App heimlich nutzt...',
  'Ein guter Grund für ein herzhaftes Lachen beim Sex...',
  'Ein Katerfrühstück nach einer langen Nacht...',
  'Ein Kostüm fürs Bett...',
  'Ein Kriterium für ein perfektes Dick-Pic...',
  'Ein passender Ort für eine illegale Rave-Party...',
  'Ein Pornodarsteller/Pornodarstellerin...',
  'Ein realistischer ekliger Fund im Bett...',
  'Ein Safeword Idee...',
  'Ein Sexspielzeug...',
  'Ein Sexting Thema...',
  'Ein Synonym für blasen...',
  'Ein Synonym für das männliche Masturbieren...',
  'Ein Synonym für das weibliche Masturbieren...',
  'Ein Synonym für lecken ...',
  'Ein Synonym für Penis...',
  'Ein Synonym für Saufen...',
  'Ein Synonym für Sex...',
  'Ein Synonym für Vagina...',
  'Ein typischer ekliger Fund in einem Mülleimer im Krankenhaus...',
  'Ein typischer ekliger Fund in einer Messi-Wohnung...',
  'Ein typischer Gedanke beim Duschen mit jemandem...',
  'Ein typischer Gedanke beim Rummachen...',
  'Ein typischer Gedanke beim Sexting...',
  'Ein typischer Gedanke beim Telefonsex...',
  'Ein typischer Gedanke nach einem One Night Stand...',
  'Ein typischer Gegenstand in einem Spionage-Kit...',
  'Ein typischer Ort für Sex...',
  'Ein typisches Getränk welches mit Vodka gemischt wird...',
  'Ein typisches Rollenspiel...',
  'Ein Verhalten wenn man Interesse vortäuscht...',
  'Ein Videospiel indem es Waffen gibt...',
  'Eine Ausrede für einen Knutschfleck...',
  'Eine Droge...',
  'Eine gute Ausrede für das Schwarzfahren in der Bahn...',
  'Eine gute Reaktion nachdem der Partner fremd gegangen ist...',
  'Eine Sexposition...',
  'Eine Sexposition für Faule...',
  'Eine typische Porno Kategorie...',
  'Etwas das man typischerweise betrunken macht und dann bereuht...',
  'Etwas das man typischerweise nur mit dem Partner macht...',
];
