// Inhalte für Spicy Intensity Level 1.
// Einfach weitere Zeilen im Array ergänzen.
window.SPICY_LEVEL_1 = [
  'Ein Accessoire...',
  'Ein Adjektiv...',
  'Ein Albumtitel...',
  'Ein alkoholisches Getränk...',
  'Ein Bauteil an einem Fahrrad...',
  'Ein Bauteil eines Autos...',
  'Ein Berg...',
  'Ein Berg...',
  'Ein Beruf...',
  'Ein Beruf im Krankenhaus...',
  'Ein Beruf mit Uniform...',
  'Ein berühmtes Gebäude...',
  'Ein Beziehungsstatus...',
  'Ein Brettspiel...',
  'Ein Brettspiel...',
  'Ein Bundesland...',
  'Ein chemisches Element...',
  'Ein Dateiformat...',
  'Ein Dessert mit Sahne...',
  'Ein Deutschrapper...',
  'Ein Ding aus Glas...',
  'Ein Ding aus Metall...',
  'Ein Ding das Licht macht...',
  'Ein Ding das man faltet...',
  'Ein Ding das man öffnet und schließt...',
  'Ein Ding das man oft am Strand findet...',
  'Ein Ding das man wirft...',
  'Ein Ding das warm macht...',
  'Ein Ding zum Aufbewahren...',
  'Ein Disney Charakter...',
  'Ein Disneyfilm...',
  'Ein elektronisches Gerät...',
  'Ein engedeutschtes Wort...',
  'Ein englisches Wort...',
  'Ein Fahrzeug mit zwei Rädern...',
  'Ein Feiertag...',
  'Ein Filmcharakter...',
  'Ein Filmgenre...',
  'Ein Filmgenre...',
  'Ein Filmtitel...',
  'Ein Filmtitel mit genau einem Wort...',
  'Ein Fisch...',
  'Ein Fluss...',
  'Ein Fluss...',
  'Ein Frauenname...',
  'Ein Fußballspieler/Fußballspielerin...',
  'Ein Fußballverein...',
  'Ein Fußballverein...',
  'Ein Gebäck beim Bäcker...',
  'Ein Gedanke beim Scrollen durch alte Chats...',
  'Ein Gefühl bei einem ersten Date...',
  'Ein Gegenstand aus Papier...',
  'Ein Gegenstand den man häufig beim Sperrmüll findet...',
  'Ein Gegenstand den man mit beiden Händen tragen muss...',
  'Ein Gegenstand den man typischerweise immer dabei hat...',
  'Ein Gegenstand den typischerweise nur Singles besitzen...',
  'Ein Gegenstand den typischerweise nur Vergebene besitzen...',
  'Ein Gegenstand der typischerweise aus Holz besteht...',
  'Ein Gegenstand der typischerweise oft verloren geht...',
  'Ein Gegenstand im Badezimmer...',
  'Ein Gegenstand im Büro...',
  'Ein Gegenstand zum schminken...',
  'Ein Gegenstand, den man beim Feiern typischerweise immer dabei hat...',
  'Ein Gegenstand, den man in einem Verbandskasten findet...',
  'Ein Gegenstand, den man typischerweise für ein Date kauft...',
  'Ein Gegenstand, den man typischerweise im Hotel mitgehen lässt...',
  'Ein Gegenstand, den man typischerweise nur in der Apotheke kaufen kann...',
  'Ein Gemüse...',
  'Ein Gerät in der Küche...',
  'Ein Gerät zum Putzen...',
  'Ein Getränk das man typischerweise warm oder auch kalt trinken kann...',
  'Ein Getränk mit Kohlensäure...',
  'Ein Getränk ohne Alkohol...',
  'Ein Gewürz...',
  'Ein Grund eifersüchtig zu sein...',
  'Ein Grund für ein schlechtes Gewissen beim Shoppen...',
  'Ein Grund für ein schlechtes Gewissen nach dem Feiern...',
  'Ein Grund für eine kleine Lüge...',
  'Ein Grund für eine Mutprobe...',
  'Ein Grund für eine rote Wange...',
  'Ein Grund für eine schlaflose Nacht...',
  'Ein Grund für eine Überraschungsparty...',
  'Ein Grund für einen Applaus...',
  'Ein Grund für einen Korb...',
  'Ein Grund für Schmetterlinge im Bauch...',
  'Ein Grund jemanden anzurufen...',
  'Ein Grund jemanden nach der Nummer zu fragen...',
  'Ein Grund jemanden nachts anzurufen...',
  'Ein Grund jemanden nicht zu antworten...',
  'Ein Grund jemanden zu blockieren...',
  'Ein Grund jemanden zu ghosten...',
  'Ein Grund jemanden zu stalken...',
  'Ein Grund sich zu entschuldigen...',
  'Ein Grund warum man beim Küssen lacht...',
  'Ein Grund warum man Nachrichten löscht...',
  'Ein Grund zum Feiern...',
  'Ein Gruß...',
  'Ein guter Grund für ein Fake-Lachen...',
  'Ein guter Grund für gute Laune...',
  'Ein Handwerksberuf...',
  'Ein Haushaltsgerät...',
  'Ein Haustier...',
  'Ein Hobby für draußen...',
  'Ein Influencer/Influencerin...',
  'Ein Insekt...',
  'Ein Instrument...',
  'Ein Jugendwort...',
  'Ein Kartenspiel...',
  'Ein Kleidungsstück für die Füße...',
  'Ein Kleidungsstück für oben...',
  'Ein Kleidungsstück nur für den Winter...',
  'Ein Land...',
  'Ein Land das eine Insel ist...',
  'Ein Land in Afrika...',
  'Ein Land in Asien...',
  'Ein Liedtitel...',
  'Ein Männername...',
  'Ein Märchen...',
  'Ein Meerestier...',
  'Ein Möbelstück im Wohnzimmer...',
  'Ein Möbelstück zum Sitzen...',
  'Ein Moderator/Moderatorin...',
  'Ein Moment zum Weinen...',
  'Ein Monat...',
  'Ein Musikgenre...',
  'Ein Nomen...',
  'Ein Objekt zum Trinken...',
  'Ein Obst das gelb ist...',
  'Ein Ort an dem man oft wartet...',
  'Ein Ort an dem man typischerweise leise ist...',
  'Ein Ort an dem man typischerweise nicht allein sein will...',
  'Ein Ort an dem man typischerweise nicht erwischt werden will...',
  'Ein Ort an dem typischerweise viele Menschen sind...',
  'Ein Ort zum Einkaufen...',
  'Ein peinlicher Moment beim ersten Date...',
  'Ein perfekter Ort für ein erstes Date...',
  'Ein Planet...',
  'Ein Pokémon...',
  'Ein Politiker/Politikerin...',
  'Ein Rapper...',
  'Ein Rapper mit einer Zahl im Namen...',
  'Ein Raubtier...',
  'Ein Sänger/Sängerin...',
  'Ein Schauspieler/Schauspielerin...',
  'Ein Schimpfwort...',
  'Ein Schmuckstück...',
  'Ein Schulfach...',
  'Ein Serientitel...',
  'Ein Sinnesorgan...',
  'Ein Songtitel...',
  'Ein Spiel für Kinder...',
  'Ein Spielzeug...',
  'Ein Spitzname für den Partner/Partnerin...',
  'Ein Sport...',
  'Ein Sport der im Team gespielt wird...',
  'Ein Sportgerät...',
  'Ein Sportler/Sportlerin...',
  'Ein Sprichwort...',
  'Ein Sternzeichen...',
  'Ein Stoff...',
  'Ein Streamer/Streamerin...',
  'Ein Superheld...',
  'Ein Supermarkt...',
  'Ein Synonym für küssen...',
  'Ein Tier auf dem Bauernhof...',
  'Ein Tier das Eier legt...',
  'Ein Tier das fliegen kann...',
  'Ein Tier das höher als ein normaler Mensch springen kann...',
  'Ein Tier das im Dunkeln jagt...',
  'Ein Tier das schneller als ein normaler Mensch rennen kann...',
  'Ein Tier das Winterschlaf hält...',
  'Ein Tier im Wald...',
  'Ein Tier im Wasser...',
  'Ein Tier mit einem harten Panzer...',
  'Ein Tier welches typischerweise auf dem Bauernhof lebt...',
  'Ein TikToker/TikTokerin...',
  'Ein Transportmittel...',
  'Ein typischer Begriff aus dem Fußball...',
  'Ein typischer Begriff aus dem Reitsport...',
  'Ein typischer Begriff aus dem Theater...',
  'Ein typischer Begriff aus dem Weltall...',
  'Ein typischer Begriff aus der Archäologie...',
  'Ein typischer Begriff aus der Architektur...',
  'Ein typischer Begriff aus der Biologie...',
  'Ein typischer Begriff aus der Botanik...',
  'Ein typischer Begriff aus der Chemie...',
  'Ein typischer Begriff aus der Computerwelt...',
  'Ein typischer Begriff aus der Elektrotechnik...',
  'Ein typischer Begriff aus der Fotografie...',
  'Ein typischer Begriff aus der Geografie...',
  'Ein typischer Begriff aus der Geschichte...',
  'Ein typischer Begriff aus der Kunst...',
  'Ein typischer Begriff aus der Landwirtschaft...',
  'Ein typischer Begriff aus der Mathematik...',
  'Ein typischer Begriff aus der Musik...',
  'Ein typischer Begriff aus der Physik...',
  'Ein typischer Begriff aus der Politik...',
  'Ein typischer Begriff aus der Schifffahrt...',
  'Ein typischer Begriff aus der Wirtschaft...',
  'Ein typischer Begriff aus der Wissenschaft...',
  'Ein typischer Fehler beim Chatten...',
  'Ein typischer Gegenstand auf einem Nachttisch...',
  'Ein typischer Gegenstand auf einem Schreibtisch...',
  'Ein typischer Gegenstand auf einem Spielplatz...',
  'Ein typischer Gegenstand aus Harry Potter...',
  'Ein typischer Gegenstand aus Pokémon...',
  'Ein typischer Gegenstand aus Star Wars...',
  'Ein typischer Gegenstand im Handschuhfach...',
  'Ein typischer Gegenstand im Schlafzimmer...',
  'Ein typischer Gegenstand im Wartezimmer...',
  'Ein typischer Gegenstand in einem Angelkoffer...',
  'Ein typischer Gegenstand in einem Badezimmerschrank...',
  'Ein typischer Gegenstand in einem Café...',
  'Ein typischer Gegenstand in einem Erste-Hilfe-Kasten...',
  'Ein typischer Gegenstand in einem Fitnessstudio...',
  'Ein typischer Gegenstand in einem Gartenhaus...',
  'Ein typischer Gegenstand in einem Hotelzimmer...',
  'Ein typischer Gegenstand in einem Kino...',
  'Ein typischer Gegenstand in einem Klassenzimmer...',
  'Ein typischer Gegenstand in einem Koffer...',
  'Ein typischer Gegenstand in einem Musuem...',
  'Ein typischer Gegenstand in einem Park...',
  'Ein typischer Gegenstand in einem Restaurant...',
  'Ein typischer Gegenstand in einem Rucksack beim Wandern...',
  'Ein typischer Gegenstand in einem Schuppen...',
  'Ein typischer Gegenstand in einem Souvenirladen...',
  'Ein typischer Gegenstand in einem Supermarktregal...',
  'Ein typischer Gegenstand in einem Verhörraum...',
  'Ein typischer Gegenstand in einem Werkzeugkoffer...',
  'Ein typischer Gegenstand in einem Zelt...',
  'Ein typischer Gegenstand in einem Zirkus...',
  'Ein typischer Gegenstand in einer Apotheke...',
  'Ein typischer Gegenstand in einer Asservatenkammer...',
  'Ein typischer Gegenstand in einer Bibliothek...',
  'Ein typischer Gegenstand in einer Garage...',
  'Ein typischer Gegenstand in einer Gefriertruhe...',
  'Ein typischer Gegenstand in einer Handtasche...',
  'Ein typischer Gegenstand in einer Küche...',
  'Ein typischer Gegenstand in einer Minibar...',
  'Ein typischer Geruch in der Küche...',
  'Ein typischer Grund zu lügen...',
  'Ein typischer Grund zu spät zu kommen...',
  'Ein typischer Kosename...',
  'Ein typischer Luxusgegenstand...',
  'Ein typischer Move auf der Tanzfläche...',
  'Ein typischer Satz beim Schlussmachen...',
  'Ein typischer Smalltalk Satz...',
  'Ein typischer Spitzname für den Ex-Partner...',
  'Ein typischer Streit in Beziehungen...',
  'Ein typischer Streitgrund...',
  'Ein typisches Frühstücksgetränk...',
  'Ein typisches Geschenk für den Chef',
  'Ein typisches Geschenk für den Partner',
  'Ein typisches Geschenk für die Schwiegermutter',
  'Ein typisches Geschenk für Frauen...',
  'Ein typisches Geschenk für Geburtstage...',
  'Ein typisches Geschenk für Kinder...',
  'Ein typisches Geschenk für Männer',
  'Ein typisches Geschenk für Weihnachten...',
  'Ein typisches Klischee auf Tinder...',
  'Ein typisches Klischee über Chefs...',
  'Ein typisches Klischee über Dating-Apps...',
  'Ein typisches Klischee über Paare...',
  'Ein typisches Klischee über Studenten...',
  'Ein typisches Klischee über Teenager...',
  'Ein typisches Problem im Job...',
  'Ein typisches Tier in deutschen Zoos...',
  'Ein typisches Valentinstag Geschenk...',
  'Ein typisches Verhalten bei Nervosität...',
  'Ein Verb...',
  'Ein Verhalten bei Stress...',
  'Ein Verkehrsmittel in der Stadt...',
  'Ein Videospiel...',
  'Ein Werbegeschenk...',
  'Ein Werkzeug für Holz...',
  'Ein Wissenschaftler/Wissenschaftlerin...',
  'Ein Wort mit genau 3 Buchstaben...',
  'Ein Wort mit genau 8 Buchstaben...',
  'Ein Wort mit mehr als 10 Buchstaben...',
  'Ein Wort mit zwei "A"...',
  'Ein YouTuber/YouTuberin...',
  'Eine App...',
  'Eine App die man typischerweise täglich nutzt...',
  'Eine Ausrede fürs nicht Antworten...',
  'Eine Automarke...',
  'Eine Automarke aus Deutschland...',
  'Eine Band...',
  'Eine bekannte Kindersendung...',
  'Eine bekannte Sehenswürdigkeit in Deutschland...',
  'Eine europäische Hauptstadt...',
  'Eine Farbe...',
  'Eine Fast Food Kette...',
  'Eine Flüssigkeit...',
  'Eine freundliche Geste...',
  'Eine Hunderasse...',
  'Eine Käsesorte...',
  'Eine Kopfbedeckung...',
  'Eine Künstliche Intelligenz...',
  'Eine Nudelsorte...',
  'Eine Obstsorte die man schälen muss...',
  'Eine Obstsorte mit Kernen...',
  'Eine Schuhmarke...',
  'Eine Serie mit mindestens 4 Staffeln...',
  'Eine Serie mit weniger als 4 Staffeln...',
  'Eine Sportart im Schnee...',
  'Eine Sportart im Wasser...',
  'Eine Sportart mit Ball...',
  'Eine Sportart ohne Ball...',
  'Eine Sprache...',
  'Eine Stadt...',
  'Eine typische Green Flag...',
  'Eine typische Red Flag...',
  'Eine typische Zutat für einen Salat...',
  'Eine Zahl...',
  'Etwas Bitteres...',
  'Etwas das man hauptsächlich im Sommer trägt...',
  'Etwas das man heimlich macht...',
  'Etwas das man im Regen benutzt...',
  'Etwas das man typischerweise im Badezimmer macht...',
  'Etwas das man typischerweise im Bett macht...',
  'Etwas das man typischerweise in der Küche macht...',
  'Etwas das man typischerweise jeden Tag macht...',
  'Etwas das man typischerweise nur abends macht...',
  'Etwas das man typischerweise nur alleine macht...',
  'Etwas das man typischerweise nur macht wenn man sturmfrei hat...',
  'Etwas das man typischerweise nur morgens macht...',
  'Etwas das man typischerweise nur zu zweit macht...',
  'Etwas das man zum Schreiben benutzt...',
  'Etwas Salziges...',
  'Etwas Saures...',
  'Etwas Saures...',
  'Etwas Scharfes...',
  'Etwas was dich vor dem Regen schützt...',
];
