// Inhalte für Spicy Intensity Level 3.
// Level 4 greift aktuell ebenfalls auf diese Datei zurück,
// bis du mir dafür eigene Inhalte oder Regeln gibst.
window.SPICY_LEVEL_3 = [
  'Ein BDSM Begriff...',
'Ein Dirty Talk Satz...',
'Ein ekliger Anblick in einer Messie-Wohnung...',
'Ein ekliger Gegenstand in einer öffentlichen Toilette...',
'Ein ekliger Geruch im Mülleimer...',
'Ein Fetisch...',
'Ein Gegenstand den man bei einem Lapdance benutzt...',
'Ein Gegenstand für Spanking...',
'Ein Gegenstand, den man im Puff sieht...',
'Ein Gegenstand, den man sich in eine Körperöffnung steckt...',
'Ein Gegenstand, der bei einer Orgie nicht fehlen darf...',
'Ein Gegenstand, der für BDSM-Spiele genutzt wird...',
'Ein Grund für ein Mord...',
'Ein Grund für eine fristlose Kündigung...',
'Ein Grund für eine fristlose Kündigung im Kindergarten...',
'Ein Grund für eine Hausdurchsuchung...',
'Ein Grund für eine internationale Fahndung...',
'Ein Grund für eine lebenslange Haftstrafe...',
'Ein Grund für eine lebenslange Haftstrafe...',
'Ein Grund für eine Massenschlägerei...',
'Ein Grund für eine öffentliche Hinrichtung im Mittelalter...',
'Ein Grund für eine Schlägerei im Club...',
'Ein Grund für eine Schlägerei im Club...',
'Ein Grund für eine schwere Körperverletzung...',
'Ein Grund für eine sofortige Flucht aus dem Land...',
'Ein Grund für eine Suchterkrankung...',
'Ein Grund für einen totalen Absturz...',
'Ein Grund für gesellschaftliche Ächtung...',
'Ein Grund warum das Kondom reißt...',
'Ein Grund, warum man im Gefängnis landet...',
'Ein illegaler Ort für Sex...',
'Ein illegaler Ort zum Konsum von Drogen...',
'Ein Kink...',
'Ein Ort für Drogenhandel...',
'Ein Ort für einen Quickie...',
'Ein Ort für illegale Glücksspiele...',
'Ein Ort für illegale Graffiti...',
'Ein Ort für illegale Müllentsorgung...',
'Ein Ort für illegale Prostitution...',
'Ein passender Ort für den Konsum von harten Drogen...',
'Ein passender Ort für eine illegale Pokerrunde...',
'Ein perfekter Ort für den Handel mit Hehlerware...',
'Ein typischer Fetisch...',
'Ein typischer Gegenstand in einem Folterkeller...',
'Ein typischer Gegenstand in einem Koffer eines Attentäters...',
'Ein typischer Gegenstand in einem Puff...',
'Ein typischer Gegenstand in einem Stripclub-Mülleimer...',
'Ein typischer Gegenstand in einer Drogenküche...',
'Ein typischer Gegenstand, den Frauen beim Masturbieren nutzen...',
'Ein typischer Gegenstand, den Männer beim Masturbieren nutzen...',
'Ein unpassender Ort für den Konsum von harten Drogen...',
'Ein unpassender Ort für einen flotten Dreier...',
'Eine Dildo Form...',
'Eine harte Beleidigung für Frauen...',
'Eine harte Beleidigung für Männer...',
'Eine illegale Droge...',
'Eine Porno Kategorie die verboten wirkt...',
'Etwas das man beim Konsum von harten Drogen verliert...',
'Etwas das man heimlich macht während der Partner schläft...',
'Etwas, das man bei einem Assjob macht...',
'Etwas, das man bei einem Blowjob denkt...',
'Etwas, das man bei einem flotten Dreier tut...',
'Etwas, das man beim Dirty Talk sagt...',
'Etwas, das man beim Konsum von harten Drogen verliert...',
'Etwas, das man beim Konsum von Pilzen sieht...',
'Etwas, das man in einem Sexshop kauft...',
];
