window.MYSTERY_SPICY_LEVEL_1 = [
  {text:"Welche zwei Mitspieler würden so garkein gutes Ehepaar abgeben?", beziehungskiller: 1, spiceCall: true},
{text:"Welche zwei Mitspieler würden das beste Pärchen abgeben?", beziehungskiller: 2, spiceCall: true},
{text:"Welche zwei Mitspieler wären das chaotischste WG-Duo?", beziehungskiller: 0, spiceCall: false},
{text:"Welche zwei Mitspieler würden das beste Good Cop und Bad Cop Duo abgeben?", beziehungskiller: 0, spiceCall: false},
{text:"Welche zwei Mitspieler würden sich ausversehen verloben?", beziehungskiller: 1, spiceCall: true},
{text:"Welcher Mitspieler hat die schönste Friseur?", beziehungskiller: 1, spiceCall: true},
{text:"Welcher Mitspieler hat das charmanteste Lachen?", beziehungskiller: 0, spiceCall: false},
{text:"Mit welchem Mitspieler würdest du JETZT am ehesten Klamotten tauschen wollen?", beziehungskiller: 0, spiceCall: false},
{text:"Mit welchem Mitspieler würdest du am ehesten dein Kleiderschrank tauschen wollen?", beziehungskiller: 0, spiceCall: false},
{text:"Welcher Mitspieler hat den besten Modegeschmack?", beziehungskiller: 0, spiceCall: false},
{text:"Welcher Mitspieler hat die schönste Stimme?", beziehungskiller: 0, spiceCall: false},
{text:"Welcher Mitspieler würde den romantischsten Liebesbrief schreiben?", beziehungskiller: 0, spiceCall: false},
{text:"Welcher der Mitspieler würde am ehesten obdachlos werden?", beziehungskiller: 0, spiceCall: false},
{text:"Welcher der Mitspieler würde den besten Straßenkünstler abgeben?", beziehungskiller: 0, spiceCall: false},
{text:"Mit welchem Tier würdest du dich selber beschreiben?", beziehungskiller: 0, spiceCall: false},
{text:"Was ist dein lieblings Tier?", beziehungskiller: 0, spiceCall: false},
{text:"Welches Alter würdest du für immer behalten wenn du müsstest?", beziehungskiller: 0, spiceCall: false},
{text:"Mit welchem Alter hattest du dein ersten richtigen Kuss?", beziehungskiller: 0, spiceCall: false},
{text:"Mit welchem Alter hattest du deine erste Beziehung?", beziehungskiller: 0, spiceCall: false},
{text:"Welche Körpergröße (in cm) findest du bei deinem Partner perfekt?", beziehungskiller: 0, spiceCall: false},
{text:"Wer ist dein lieblings Influencer?", beziehungskiller: 0, spiceCall: false},
];
