window.MYSTERY_SPICY_LEVEL_2 = [
  {text:"Auf welche Farbe würdest du das Zimmerlicht stellen für eine heiße Nacht?", beziehungskiller: 0, spiceCall: false, tipp1:"Stimmung", tipp2:"Licht"},
{text:"Auf welchem Körperteil liebst du Küsse am meisten?", beziehungskiller: 0, spiceCall: false, tipp1:"Nähe", tipp2:"Küsse"},
{text:"Für wie viel Geld würdest du ein Jahr lang auf Alkohol verzichten?", beziehungskiller: 0, spiceCall: false, tipp1:"Verzicht", tipp2:"Alkohol"},
{text:"Für wieviel Geld würdest du einen kleinen Finger abhacken?", beziehungskiller: 0, spiceCall: false, tipp1:"Grenze", tipp2:"Finger"},
{text:"Für wieviel Geld würdest du einen unattraktiven fremden Menschen küssen?", beziehungskiller: 0, spiceCall: false, tipp1:"Preis", tipp2:"Kuss"},
{text:"Für wieviel Geld würdest du Sex mit einem Obdachlosen haben?", beziehungskiller: 0, spiceCall: false, tipp1:"Grenze", tipp2:"Sex"},
{text:"Mit welchem Alter hattest du dein erstes Mal?", beziehungskiller: 0, spiceCall: false, tipp1:"Vergangenheit", tipp2:"Sex"},
{text:"Mit welchem Mitspieler könntest du dir am ehesten eine Beziehung vorstellen?", beziehungskiller: 2, spiceCall: true, tipp1:"Dating", tipp2:"Beziehung"},
{text:"Mit welchem Mitspieler würdest du am liebsten 24 Stunden verbringen?", beziehungskiller: 1, spiceCall: true, tipp1:"Nähe", tipp2:"Zeit"},
{text:"Mit welchem Tier würdest du dein Intimbereich beschreiben?", beziehungskiller: 0, spiceCall: false, tipp1:"Vergleich", tipp2:"Intimbereich"},
{text:"Nach dem wievielten Date hälst du Rummachen für angebracht?", beziehungskiller: 0, spiceCall: false, tipp1:"Dating", tipp2:"Küssen"},
{text:"Nach dem wievielten Date hälst du Sex für angebracht?", beziehungskiller: 0, spiceCall: false, tipp1:"Dating", tipp2:"Sex"},
{text:"Von welchem Mitspieler würdest du am ehesten ein Striptease bekommen wollen?", beziehungskiller: 2, spiceCall: true, tipp1:"Erotik", tipp2:"Striptease"},
{text:"Von welchem Mitspieler würdest du am liebsten dessen Fantasien erfahren wollen?", beziehungskiller: 0, spiceCall: false, tipp1:"Neugier", tipp2:"Fantasien"},
{text:"Wann hast du am liebsten Sex?", beziehungskiller: 0, spiceCall: false, tipp1:"Intimität", tipp2:"Zeitpunkt"},
{text:"Wann hast du dein letztes Nude erhalten?", beziehungskiller: 0, spiceCall: false, tipp1:"Chat", tipp2:"Nude"},
{text:"Wann hast du dein letztes Nude versendet ?", beziehungskiller: 0, spiceCall: false, tipp1:"Chat", tipp2:"Nude"},
{text:"Wann hattest du dein letzten Orgasmus (Sex/Masturbation)?", beziehungskiller: 0, spiceCall: false, tipp1:"Intimität", tipp2:"Orgasmus"},
{text:"Was denkst du welchen Bodycount Fremde bei dir schätzen würden?", beziehungskiller: 0, spiceCall: false, tipp1:"Eindruck", tipp2:"Bodycount"},
{text:"Was ist deine liebste Sexstellung?", beziehungskiller: 0, spiceCall: false, tipp1:"Sex", tipp2:"Stellung"},
{text:"Welche Droge magst du am liebsten?", beziehungskiller: 0, spiceCall: false, tipp1:"Rausch", tipp2:"Droge"},
{text:"Welche eine Klamotte würdest du beim Sex anlassen wenn du müsstest?", beziehungskiller: 0, spiceCall: false, tipp1:"Kleidung", tipp2:"Sex"},
{text:"Welche Farbe findest du bei Lippenstift am heißesten?", beziehungskiller: 0, spiceCall: false, tipp1:"Aussehen", tipp2:"Lippenstift"},
{text:"Welche Farbe findest du bei Unterwäsche am heißesten?", beziehungskiller: 0, spiceCall: false, tipp1:"Erotik", tipp2:"Unterwäsche"},
{text:"Welche Penisgröße (in cm) würdest du als perfekt bezeichnen?", beziehungskiller: 0, spiceCall: false, tipp1:"Körper", tipp2:"Penis"},
{text:"Welche Sexstellung findest du am unbequemsten?", beziehungskiller: 0, spiceCall: false, tipp1:"Sex", tipp2:"Stellung"},
{text:"Welche zwei Mitspieler könnten den besten Dirty Talk miteinander führen?", beziehungskiller: 1, spiceCall: true, tipp1:"Erotik", tipp2:"Dirtytalk"},
{text:"Welche zwei Mitspieler würden am ehesten eine Fake-Beziehung führen?", beziehungskiller: 1, spiceCall: true, tipp1:"Schauspiel", tipp2:"Beziehung"},
{text:"Welche zwei Mitspieler würden sich ausversehen auf einer Swingerparty treffen?", beziehungskiller: 1, spiceCall: true, tipp1:"Erotik", tipp2:"Swinger"},
{text:"Welchen Beruf findest du so richtig sexy?", beziehungskiller: 0, spiceCall: false, tipp1:"Anziehung", tipp2:"Beruf"},
{text:"Welchen Beruf findest du so richtige unsexy?", beziehungskiller: 0, spiceCall: false, tipp1:"Abturn", tipp2:"Beruf"},
{text:"Welchen Mitspieler dürfte dein Kind am ehesten daten?", beziehungskiller: 0, spiceCall: false, tipp1:"Vertrauen", tipp2:"Dating"},
{text:"Welchen Mitspieler dürfte dein Kind nicht daten?", beziehungskiller: 0, spiceCall: false, tipp1:"Misstrauen", tipp2:"Dating"},
{text:"Welchen Mitspieler würdest du am ehesten heiraten?", beziehungskiller: 2, spiceCall: true, tipp1:"Liebe", tipp2:"Heirat"},
{text:"Welcher Mitspieler denkst du ist der größte Player?", beziehungskiller: 0, spiceCall: false, tipp1:"Dating", tipp2:"Player"},
{text:"Welcher Mitspieler denkst du kann am heißesten strippen/tanzen?", beziehungskiller: 2, spiceCall: true, tipp1:"Erotik", tipp2:"Tanzen"},
{text:"Welcher Mitspieler hat den schönsten Körper?", beziehungskiller: 2, spiceCall: true, tipp1:"Aussehen", tipp2:"Körper"},
{text:"Welcher Mitspieler hat die schönsten Lippen?", beziehungskiller: 2, spiceCall: true, tipp1:"Aussehen", tipp2:"Lippen"},
{text:"Welcher Mitspieler sollte am ehesten mit Onlyfans anfangen?", beziehungskiller: 0, spiceCall: false, tipp1:"Erotik", tipp2:"OnlyFans"},
{text:"Welcher Mitspieler würde am ehesten in einem Stripclub arbeiten und erfolg haben?", beziehungskiller: 0, spiceCall: false, tipp1:"Erotik", tipp2:"Stripclub"},
{text:"Welcher Mitspieler würde am ehesten mit einer verheirateten Person schlafen?", beziehungskiller: 0, spiceCall: false, tipp1:"Moral", tipp2:"Affäre"},
{text:"Welcher Mitspieler würde die beste Sugar Mommy oder Daddy abgeben?", beziehungskiller: 0, spiceCall: false, tipp1:"Luxus", tipp2:"Sugar"},
{text:"Welches Getränk mischt du am liebsten mit Alkohol?", beziehungskiller: 0, spiceCall: false, tipp1:"Trinken", tipp2:"Mischen"},
{text:"Welches Körperteil findest du an einem Partner am uninteressantesten?", beziehungskiller: 0, spiceCall: false, tipp1:"Körper", tipp2:"Uninteressant"},
{text:"Welches Körperteil magst du an einem Partner am meisten?", beziehungskiller: 0, spiceCall: false, tipp1:"Körper", tipp2:"Favorit"},
{text:"Welches Körperteil musst du nackt sehen und wirst direkt horny?", beziehungskiller: 0, spiceCall: false, tipp1:"Anziehung", tipp2:"Nackt"},
{text:"Welches Wort beschreibt dein letzten Sex?", beziehungskiller: 0, spiceCall: false, tipp1:"Rückblick", tipp2:"Sex"},
{text:"Welches Wort beschreibt dein Sexleben am besten?", beziehungskiller: 0, spiceCall: false, tipp1:"Selbstbild", tipp2:"Sexleben"},
{text:"Welches Wort gibt dir direkt ein Turn-off?", beziehungskiller: 0, spiceCall: false, tipp1:"Sprache", tipp2:"Abturn"},
{text:"Wer der Mitspieler denkst du bumst am besten?", beziehungskiller: 0, spiceCall: false, tipp1:"Einschätzung", tipp2:"Sex"},
{text:"Wer der Mitspieler denkst du hat den höchsten Bodycount?", beziehungskiller: 0, spiceCall: false, tipp1:"Einschätzung", tipp2:"Bodycount"},
{text:"Wer der Mitspieler denkst du hat den höchsten Kisscount?", beziehungskiller: 0, spiceCall: false, tipp1:"Einschätzung", tipp2:"Küsse"},
{text:"Wer der Mitspieler denkst du küsst am besten?", beziehungskiller: 0, spiceCall: false, tipp1:"Einschätzung", tipp2:"Küssen"},
{text:"Wie alt warst du bei deinem ersten richtigen Vollrausch?", beziehungskiller: 0, spiceCall: false, tipp1:"Vergangenheit", tipp2:"Alkohol"},
{text:"Wie hoch ist dein Bodycount?", beziehungskiller: 0, spiceCall: false, tipp1:"Sexleben", tipp2:"Anzahl"},
{text:"Wie hoch ist dein Kisscount?", beziehungskiller: 0, spiceCall: false, tipp1:"Dating", tipp2:"Anzahl"},
{text:"Wie lange war dein letzter Sex (in Minuten)?", beziehungskiller: 0, spiceCall: false, tipp1:"Zeit", tipp2:"Sex"},
{text:"Wie oft in der Woche masturbierst du?", beziehungskiller: 0, spiceCall: false, tipp1:"Gewohnheit", tipp2:"Masturbation"},
{text:"Wieviele Jahre lagen zwischen dir und deinem ältesten Sexpartner?", beziehungskiller: 0, spiceCall: false, tipp1:"Alter", tipp2:"Unterschied"},
{text:"Wieviele Kinder im Alter von 6 Jahren würdest du in einem Kampf besiegen?", beziehungskiller: 0, spiceCall: false, tipp1:"Kampf", tipp2:"Kinder"},
];
