window.MYSTERY_SPICY_LEVEL_1 = [
  {text:"Auf welche Eigenschaft achtest du als erstes bei Menschen?", beziehungskiller: 0, spiceCall: false, tipp1:"Eindruck", tipp2:"Charakter"},
{text:"Für wie viel Geld würdest du dir eine Glatze rasieren?", beziehungskiller: 0, spiceCall: false, tipp1:"Mutprobe", tipp2:"Haare"},
{text:"Für wie viel Geld würdest du einen Monat komplett auf Social Media verzichten?", beziehungskiller: 0, spiceCall: false, tipp1:"Verzicht", tipp2:"Online"},
{text:"Für wieviel Geld würdest du eine Woche ins Gefängnis gehen?", beziehungskiller: 0, spiceCall: false, tipp1:"Preis", tipp2:"Haft"},
{text:"In welchem Schulfach hattest du deine schlechteste Note?", beziehungskiller: 0, spiceCall: false, tipp1:"Schule", tipp2:"Fach"},
{text:"Mit welchem Alter hattest du dein ersten richtigen Kuss?", beziehungskiller: 0, spiceCall: false, tipp1:"Vergangenheit", tipp2:"Kuss"},
{text:"Mit welchem Alter hattest du deine erste Beziehung?", beziehungskiller: 0, spiceCall: false, tipp1:"Vergangenheit", tipp2:"Beziehung"},
{text:"Mit welchem Mitspieler würdest du am ehesten dein Kleiderschrank tauschen wollen?", beziehungskiller: 0, spiceCall: false, tipp1:"Stil", tipp2:"Kleiderschrank"},
{text:"Mit welchem Mitspieler würdest du JETZT am ehesten Klamotten tauschen wollen?", beziehungskiller: 0, spiceCall: false, tipp1:"Outfit", tipp2:"Kleidung"},
{text:"Mit welchem Tier würdest du dich selber beschreiben?", beziehungskiller: 0, spiceCall: false, tipp1:"Vergleich", tipp2:"Tier"},
{text:"Was findest du romantisch, obwohl es eigentlich ziemlich kitschig ist?", beziehungskiller: 0, spiceCall: false, tipp1:"Gefühle", tipp2:"Kitsch"},
{text:"Was ist dein lieblings Tier?", beziehungskiller: 0, spiceCall: false, tipp1:"Favorit", tipp2:"Tier"},
{text:"Was ist dein Lieblings Wochentag?", beziehungskiller: 0, spiceCall: false, tipp1:"Alltag", tipp2:"Wochentag"},
{text:"Was ist dein Lieblingsfilm?", beziehungskiller: 0, spiceCall: false, tipp1:"Unterhaltung", tipp2:"Film"},
{text:"Was ist deine größte Angst in Leben?", beziehungskiller: 0, spiceCall: false, tipp1:"Gefühl", tipp2:"Angst"},
{text:"Was ist deiner Meinung nach völlig unterbewertet?", beziehungskiller: 0, spiceCall: false, tipp1:"Meinung", tipp2:"Unterschätzt"},
{text:"Was ist eine Greenflag für dich?", beziehungskiller: 0, spiceCall: false, tipp1:"Dating", tipp2:"Positiv"},
{text:"Was ist eine Redflag für dich?", beziehungskiller: 0, spiceCall: false, tipp1:"Dating", tipp2:"Warnsignal"},
{text:"Was ist für dich die attraktivste Charaktereigenschaft bei einem Menschen?", beziehungskiller: 0, spiceCall: false, tipp1:"Anziehung", tipp2:"Charakter"},
{text:"Was ist für dich komplett überbewertet?", beziehungskiller: 0, spiceCall: false, tipp1:"Meinung", tipp2:"Überschätzt"},
{text:"Was macht einen Menschen für dich sofort sympathisch?", beziehungskiller: 0, spiceCall: false, tipp1:"Eindruck", tipp2:"Sympathie"},
{text:"Was macht einen Menschen für dich sofort unsympathisch?", beziehungskiller: 0, spiceCall: false, tipp1:"Eindruck", tipp2:"Abneigung"},
{text:"Was war als Kind dein Lieblingsessen?", beziehungskiller: 0, spiceCall: false, tipp1:"Kindheit", tipp2:"Essen"},
{text:"Was war als Kind deine Lieblingsserie?", beziehungskiller: 0, spiceCall: false, tipp1:"Kindheit", tipp2:"Serie"},
{text:"Was war das teuerste Ding, das du dir selbst gekauft hast?", beziehungskiller: 0, spiceCall: false, tipp1:"Geld", tipp2:"Kauf"},
{text:"Was war dein erstes eigenes Handy?", beziehungskiller: 0, spiceCall: false, tipp1:"Technik", tipp2:"Handy"},
{text:"Was war dein erstes Konzert?", beziehungskiller: 0, spiceCall: false, tipp1:"Musik", tipp2:"Konzert"},
{text:"Was war dein peinlichster Modetrend, den du selbst mitgemacht hast?", beziehungskiller: 0, spiceCall: false, tipp1:"Vergangenheit", tipp2:"Mode"},
{text:"Was war dein schlimmster Fehlkauf?", beziehungskiller: 0, spiceCall: false, tipp1:"Geld", tipp2:"Fehlkauf"},
{text:"Was war die schlechteste Note, die du jemals bekommen hast?", beziehungskiller: 0, spiceCall: false, tipp1:"Schule", tipp2:"Note"},
{text:"Welche Angewohnheit anderer Menschen nervt dich am meisten?", beziehungskiller: 0, spiceCall: false, tipp1:"Alltag", tipp2:"Nervig"},
{text:"Welche App würdest du löschen wenn du müsstest?", beziehungskiller: 0, spiceCall: false, tipp1:"Handy", tipp2:"App"},
{text:"Welche Eigenschaft an dir selbst magst du am meisten?", beziehungskiller: 0, spiceCall: false, tipp1:"Selbstbild", tipp2:"Stärke"},
{text:"Welche Eigenschaft an dir würdest du gerne ändern?", beziehungskiller: 0, spiceCall: false, tipp1:"Selbstbild", tipp2:"Schwäche"},
{text:"Welche Farbe hatte bei dir der Mathehefter?", beziehungskiller: 0, spiceCall: false, tipp1:"Schule", tipp2:"Farbe"},
{text:"Welche Jahreszeit magst du am liebsten?", beziehungskiller: 0, spiceCall: false, tipp1:"Wetter", tipp2:"Jahreszeit"},
{text:"Welche Jahreszeit magst du am wenigsten?", beziehungskiller: 0, spiceCall: false, tipp1:"Wetter", tipp2:"Jahreszeit"},
{text:"Welche Körpergröße (in cm) findest du bei deinem Partner perfekt?", beziehungskiller: 0, spiceCall: false, tipp1:"Dating", tipp2:"Größe"},
{text:"Welche Uhrzeit am Tag magst du am liebsten?", beziehungskiller: 0, spiceCall: false, tipp1:"Tagesablauf", tipp2:"Uhrzeit"},
{text:"Welche zwei Mitspieler wären das chaotischste WG-Duo?", beziehungskiller: 0, spiceCall: false, tipp1:"Zusammenleben", tipp2:"Chaos"},
{text:"Welche zwei Mitspieler würden das beste Good Cop und Bad Cop Duo abgeben?", beziehungskiller: 0, spiceCall: false, tipp1:"Rollen", tipp2:"Polizei"},
{text:"Welche zwei Mitspieler würden das beste Pärchen abgeben?", beziehungskiller: 2, spiceCall: true, tipp1:"Liebe", tipp2:"Pärchen"},
{text:"Welche zwei Mitspieler würden sich ausversehen verloben?", beziehungskiller: 1, spiceCall: true, tipp1:"Liebe", tipp2:"Verlobung"},
{text:"Welche zwei Mitspieler würden so garkein gutes Ehepaar abgeben?", beziehungskiller: 1, spiceCall: true, tipp1:"Beziehung", tipp2:"Ehe"},
{text:"Welchem Mitspieler würdest du am ehesten dein Handy für einen ganzen Tag anvertrauen?", beziehungskiller: 0, spiceCall: false, tipp1:"Vertrauen", tipp2:"Handy"},
{text:"Welchem Mitspieler würdest du am ehesten zutrauen, auszuwandern?", beziehungskiller: 0, spiceCall: false, tipp1:"Zukunft", tipp2:"Ausland"},
{text:"Welchem Mitspieler würdest du dein Handy am wenigsten gerne entsperrt geben?", beziehungskiller: 0, spiceCall: false, tipp1:"Privatsphäre", tipp2:"Handy"},
{text:"Welchen Geruch findest du besonders angenehm?", beziehungskiller: 0, spiceCall: false, tipp1:"Sinne", tipp2:"Duft"},
{text:"Welchen Geruch kannst du überhaupt nicht ausstehen?", beziehungskiller: 0, spiceCall: false, tipp1:"Sinne", tipp2:"Geruch"},
{text:"Welchen Traumberuf hattest du als Kind?", beziehungskiller: 0, spiceCall: false, tipp1:"Kindheit", tipp2:"Beruf"},
{text:"Welcher der Mitspieler würde am ehesten obdachlos werden?", beziehungskiller: 0, spiceCall: false, tipp1:"Zukunft", tipp2:"Obdachlos"},
{text:"Welcher der Mitspieler würde den besten Straßenkünstler abgeben?", beziehungskiller: 0, spiceCall: false, tipp1:"Talent", tipp2:"Straße"},
{text:"Welcher Emoji gibt dir ein Ick?", beziehungskiller: 0, spiceCall: false, tipp1:"Chat", tipp2:"Emoji"},
{text:"Welcher Mitspieler hat das charmanteste Lachen?", beziehungskiller: 0, spiceCall: false, tipp1:"Ausstrahlung", tipp2:"Lachen"},
{text:"Welcher Mitspieler hat den besten Modegeschmack?", beziehungskiller: 0, spiceCall: false, tipp1:"Stil", tipp2:"Mode"},
{text:"Welcher Mitspieler hat die schönste Friseur?", beziehungskiller: 1, spiceCall: true, tipp1:"Aussehen", tipp2:"Haare"},
{text:"Welcher Mitspieler hat die schönste Stimme?", beziehungskiller: 0, spiceCall: false, tipp1:"Klang", tipp2:"Stimme"},
{text:"Welcher Mitspieler hätte das größte Potenzial für eine geheime Doppelidentität?", beziehungskiller: 0, spiceCall: false, tipp1:"Geheimnis", tipp2:"Doppelleben"},
{text:"Welcher Mitspieler hätte deiner Meinung nach die besten Chancen bei einer Dating-App?", beziehungskiller: 0, spiceCall: false, tipp1:"Dating", tipp2:"Matches"},
{text:"Welcher Mitspieler kennt dich am besten?", beziehungskiller: 0, spiceCall: false, tipp1:"Nähe", tipp2:"Vertrauen"},
{text:"Welcher Mitspieler kennt dich am wenigsten?", beziehungskiller: 0, spiceCall: false, tipp1:"Distanz", tipp2:"Wissen"},
{text:"Welcher Mitspieler könnte am ehesten berühmt werden?", beziehungskiller: 0, spiceCall: false, tipp1:"Erfolg", tipp2:"Berühmt"},
{text:"Welcher Mitspieler könnte am ehesten eine Sekte gründen?", beziehungskiller: 0, spiceCall: false, tipp1:"Einfluss", tipp2:"Sekte"},
{text:"Welcher Mitspieler könnte dich am besten bei deinen Eltern vertreten?", beziehungskiller: 0, spiceCall: false, tipp1:"Familie", tipp2:"Vertretung"},
{text:"Welcher Mitspieler könnte dich am schnellsten überreden, etwas Dummes zu machen?", beziehungskiller: 0, spiceCall: false, tipp1:"Einfluss", tipp2:"Überredung"},
{text:"Welcher Mitspieler könnte dich am überzeugendsten imitieren?", beziehungskiller: 0, spiceCall: false, tipp1:"Humor", tipp2:"Imitation"},
{text:"Welcher Mitspieler wäre bei einer Zombie-Apokalypse als erster weg?", beziehungskiller: 0, spiceCall: false, tipp1:"Überleben", tipp2:"Zombie"},
{text:"Welcher Mitspieler wäre der beliebteste Lehrer?", beziehungskiller: 0, spiceCall: false, tipp1:"Schule", tipp2:"Lehrer"},
{text:"Welcher Mitspieler wäre der beste Chef?", beziehungskiller: 0, spiceCall: false, tipp1:"Arbeit", tipp2:"Chef"},
{text:"Welcher Mitspieler wäre der beste Politiker?", beziehungskiller: 0, spiceCall: false, tipp1:"Macht", tipp2:"Politik"},
{text:"Welcher Mitspieler wäre der schlechteste Politiker?", beziehungskiller: 0, spiceCall: false, tipp1:"Macht", tipp2:"Politik"},
{text:"Welcher Mitspieler wäre der schlimmste Chef?", beziehungskiller: 0, spiceCall: false, tipp1:"Arbeit", tipp2:"Chef"},
{text:"Welcher Mitspieler wäre der schlimmste Lehrer?", beziehungskiller: 0, spiceCall: false, tipp1:"Schule", tipp2:"Lehrer"},
{text:"Welcher Mitspieler wird als erster/nächstes heiraten?", beziehungskiller: 0, spiceCall: false, tipp1:"Zukunft", tipp2:"Hochzeit"},
{text:"Welcher Mitspieler würde als erster/nächstes ins Gefängnis gehen?", beziehungskiller: 0, spiceCall: false, tipp1:"Zukunft", tipp2:"Gefängnis"},
{text:"Welcher Mitspieler würde am ehesten aus Versehen viral gehen?", beziehungskiller: 0, spiceCall: false, tipp1:"Internet", tipp2:"Viral"},
{text:"Welcher Mitspieler würde am ehesten bei einer Realityshow mitmachen?", beziehungskiller: 0, spiceCall: false, tipp1:"Fernsehen", tipp2:"Reality"},
{text:"Welcher Mitspieler würde am ehesten dein Geheimnis aus Versehen weitererzählen?", beziehungskiller: 0, spiceCall: false, tipp1:"Vertrauen", tipp2:"Geheimnis"},
{text:"Welcher Mitspieler würde bei einer Zombie-Apokalypse am längsten überleben?", beziehungskiller: 0, spiceCall: false, tipp1:"Überleben", tipp2:"Zombie"},
{text:"Welcher Mitspieler würde den romantischsten Liebesbrief schreiben?", beziehungskiller: 0, spiceCall: false, tipp1:"Liebe", tipp2:"Brief"},
{text:"Welcher Mitspieler würde einen Lottogewinn am schnellsten ausgeben?", beziehungskiller: 0, spiceCall: false, tipp1:"Geld", tipp2:"Lotto"},
{text:"Welches Alter würdest du für immer behalten wenn du müsstest?", beziehungskiller: 0, spiceCall: false, tipp1:"Alter", tipp2:"Ewigkeit"},
{text:"Welches Essen könntest du dein Leben lang jeden Tag essen?", beziehungskiller: 0, spiceCall: false, tipp1:"Essen", tipp2:"Dauer"},
{text:"Welches Fach in der Schule hast du gehasst?", beziehungskiller: 0, spiceCall: false, tipp1:"Schule", tipp2:"Fach"},
{text:"Welches Hobby hast du irgendwann aufgegeben?", beziehungskiller: 0, spiceCall: false, tipp1:"Freizeit", tipp2:"Hobby"},
{text:"Welches Instrument findest du attraktiv wenn es jemand spielen kann?", beziehungskiller: 0, spiceCall: false, tipp1:"Musik", tipp2:"Instrument"},
{text:"Welches Instrument findest du unattraktiv wenn es jemand spielen kann?", beziehungskiller: 0, spiceCall: false, tipp1:"Musik", tipp2:"Instrument"},
{text:"Wenn du einen Tag im Leben eines Mitspielers verbringen könntest, wen würdest du wählen?", beziehungskiller: 0, spiceCall: false, tipp1:"Perspektive", tipp2:"Mitspieler"},
{text:"Wenn du einen Tag im Leben eines Prominenten verbringen könntest, wen würdest du wählen?", beziehungskiller: 0, spiceCall: false, tipp1:"Perspektive", tipp2:"Prominent"},
{text:"Wenn du für einen Monat auf eine Sache verzichten müsstest, was wäre am schwierigsten?", beziehungskiller: 0, spiceCall: false, tipp1:"Verzicht", tipp2:"Gewohnheit"},
{text:"Wenn du sofort eine Sprache perfekt sprechen könntest, welche würdest du wählen?", beziehungskiller: 0, spiceCall: false, tipp1:"Kommunikation", tipp2:"Sprache"},
{text:"Wer ist dein lieblings Influencer?", beziehungskiller: 0, spiceCall: false, tipp1:"Internet", tipp2:"Influencer"},
{text:"Wie ist deine Körpergröße?", beziehungskiller: 0, spiceCall: false, tipp1:"Körper", tipp2:"Größe"},
{text:"Wie viele Länder hast du ungefähr schon besucht?", beziehungskiller: 0, spiceCall: false, tipp1:"Reisen", tipp2:"Länder"},
{text:"Wie viele Stunden schläfst du ungefähr pro Tag?", beziehungskiller: 0, spiceCall: false, tipp1:"Alltag", tipp2:"Schlaf"},
{text:"Wie würdest du dich Optisch von 1-10 ranken?", beziehungskiller: 0, spiceCall: false, tipp1:"Selbstbild", tipp2:"Aussehen"},
{text:"Wieviele Geschwister hast du?", beziehungskiller: 0, spiceCall: false, tipp1:"Familie", tipp2:"Geschwister"},
{text:"Wofür gibst du am liebsten Geld aus?", beziehungskiller: 0, spiceCall: false, tipp1:"Geld", tipp2:"Ausgaben"},
];
