window.MYSTERY_SPICY_LEVEL_2 = [
  {text:"Welche zwei Mitspieler würden am ehesten eine Fake-Beziehung führen?", beziehungskiller: 1, spiceCall: true},
{text:"Welche zwei Mitspieler würden sich ausversehen auf einer Swingerparty treffen?", beziehungskiller: 1, spiceCall: true},
{text:"Welche zwei Mitspieler könnten den besten Dirty Talk miteinander führen?", beziehungskiller: 1, spiceCall: true},
{text:"Welchen Mitspieler dürfte dein Kind nicht daten?", beziehungskiller: 0, spiceCall: false},
{text:"Welchen Mitspieler dürfte dein Kind am ehesten daten?", beziehungskiller: 0, spiceCall: false},
{text:"Mit welchem Mitspieler könntest du dir am ehesten eine Beziehung vorstellen?", beziehungskiller: 2, spiceCall: true},
{text:"Wer der Mitspieler denkst du hat den höchsten Bodycount?", beziehungskiller: 0, spiceCall: false},
{text:"Wer der Mitspieler denkst du hat den höchsten Kisscount?", beziehungskiller: 0, spiceCall: false},
{text:"Mit welchem Mitspieler würdest du am liebsten 24 Stunden verbringen?", beziehungskiller: 1, spiceCall: true},
{text:"Welcher Mitspieler hat den schönsten Körper?", beziehungskiller: 2, spiceCall: true},
{text:"Welcher Mitspieler denkst du kann am heißesten strippen/tanzen?", beziehungskiller: 2, spiceCall: true},
{text:"Welchen Mitspieler würdest du am ehesten heiraten?", beziehungskiller: 2, spiceCall: true},
{text:"Welcher Mitspieler denkst du ist der größte Player?", beziehungskiller: 0, spiceCall: false},
{text:"Welcher Mitspieler sollte am ehesten mit Onlyfans anfangen?", beziehungskiller: 0, spiceCall: false},
{text:"Von welchem Mitspieler würdest du am ehesten ein Striptease bekommen wollen?", beziehungskiller: 2, spiceCall: true},
{text:"Welcher Mitspieler würde am ehesten in einem Stripclub arbeiten und erfolg haben?", beziehungskiller: 0, spiceCall: false},
{text:"Welcher Mitspieler würde am ehesten mit einer verheirateten Person schlafen?", beziehungskiller: 0, spiceCall: false},
{text:"Welcher Mitspieler würde die beste Sugar Mommy oder Daddy abgeben?", beziehungskiller: 0, spiceCall: false},
{text:"Von welchem Mitspieler würdest du am liebsten dessen Fantasien erfahren wollen?", beziehungskiller: 0, spiceCall: false},
{text:"Welcher Mitspieler hat die schönsten Lippen?", beziehungskiller: 2, spiceCall: true},
{text:"Wer der Mitspieler denkst du küsst am besten?", beziehungskiller: 0, spiceCall: false},
{text:"Wer der Mitspieler denkst du bumst am besten?", beziehungskiller: 0, spiceCall: false},
{text:"Mit welchem Tier würdest du dein Intimbereich beschreiben?", beziehungskiller: 0, spiceCall: false},
{text:"Welche Farbe findest du bei Unterwäsche am heißesten?", beziehungskiller: 0, spiceCall: false},
{text:"Welche Farbe findest du bei Lippenstift am heißesten?", beziehungskiller: 0, spiceCall: false},
{text:"Auf welche Farbe würdest du das Zimmerlicht stellen für eine heiße Nacht?", beziehungskiller: 0, spiceCall: false},
{text:"Welches Körperteil magst du an einem Partner am meisten?", beziehungskiller: 0, spiceCall: false},
{text:"Welches Körperteil findest du an einem Partner am uninteressantesten?", beziehungskiller: 0, spiceCall: false},
{text:"Wann hattest du dein letzten Orgasmus (Sex/Masturbation)?", beziehungskiller: 0, spiceCall: false},
{text:"Wann hast du dein letztes Nude versendet ?", beziehungskiller: 0, spiceCall: false},
{text:"Wann hast du dein letztes Nude erhalten?", beziehungskiller: 0, spiceCall: false},
{text:"Welches Wort gibt dir direkt ein Turn-off?", beziehungskiller: 0, spiceCall: false},
{text:"Welches Wort beschreibt dein letzten Sex?", beziehungskiller: 0, spiceCall: false},
{text:"Welches Wort beschreibt dein Sexleben am besten?", beziehungskiller: 0, spiceCall: false},
{text:"Welchen Beruf findest du so richtig sexy?", beziehungskiller: 0, spiceCall: false},
{text:"Welchen Beruf findest du so richtige unsexy?", beziehungskiller: 0, spiceCall: false},
{text:"Was ist deine liebste Sexstellung?", beziehungskiller: 0, spiceCall: false},
{text:"Welche Sexstellung findest du am unbequemsten?", beziehungskiller: 0, spiceCall: false},
{text:"Welches Körperteil musst du nackt sehen und wirst direkt horny?", beziehungskiller: 0, spiceCall: false},
{text:"Auf welchem Körperteil liebst du Küsse am meisten?", beziehungskiller: 0, spiceCall: false},
{text:"Wie hoch ist dein Bodycount?", beziehungskiller: 0, spiceCall: false},
{text:"Was denkst du welchen Bodycount Fremde bei dir schätzen würden?", beziehungskiller: 0, spiceCall: false},
{text:"Mit welchem Alter hattest du dein erstes Mal?", beziehungskiller: 0, spiceCall: false},
{text:"Wieviele Jahre lagen zwischen dir und deinem ältesten Sexpartner?", beziehungskiller: 0, spiceCall: false},
{text:"Wie hoch ist dein Kisscount?", beziehungskiller: 0, spiceCall: false},
{text:"Welche Penisgröße (in cm) würdest du als perfekt bezeichnen?", beziehungskiller: 0, spiceCall: false},
{text:"Wie lange war dein letzter Sex (in Minuten)?", beziehungskiller: 0, spiceCall: false},
{text:"Nach dem wievielten Date hälst du Sex für angebracht?", beziehungskiller: 0, spiceCall: false},
{text:"Nach dem wievielten Date hälst du Rummachen für angebracht?", beziehungskiller: 0, spiceCall: false},
];
